project_id = "jcllcrvomxdrhtkqpcbr"

[functions.news-aggregator]
verify_jwt = false

[functions.crypto-prices]
verify_jwt = false

[functions.market-prefetch]
verify_jwt = false

[functions.token-prices-refresh]
verify_jwt = false

[functions.orderbook-proxy]
verify_jwt = false

[functions.tv-symbol-resolver]
verify_jwt = false

[functions.market-intel-ai]
verify_jwt = false

[functions.evm-swap]
verify_jwt = false

[functions.evm-approve]
verify_jwt = false

[functions.wc-project]
verify_jwt = false

[functions.sol-siws-nonce]
verify_jwt = false

[functions.sol-siws-verify]
verify_jwt = false

[functions.jupiter-swap]
verify_jwt = false

[functions.siwe-verify]
verify_jwt = false

[functions.limit-order-create]
verify_jwt = false

[functions.limit-order-cancel]
verify_jwt = false

[functions.limit-order-executor]
verify_jwt = false

[functions.jup-lo-open]
verify_jwt = false

[functions.jup-lo-create]
verify_jwt = false

[functions.jup-lo-cancel]
verify_jwt = false

[functions.jup-lo-execute]
verify_jwt = false

[functions.order-history-log]
verify_jwt = false

[functions.pump-create-wallet]
verify_jwt = false

[functions.pump-trade]
verify_jwt = false

[functions.dextools-proxy]
verify_jwt = false

# Cron jobs to keep DB cache fresh
[[cron.jobs]]
name = "market-prefetch-hourly"
schedule = "0 * * * *"
endpoint = "/functions/v1/market-prefetch?refresh=true&pages=2"

[[cron.jobs]]
name = "token-prices-refresh-3min"
schedule = "*/3 * * * *"
endpoint = "/functions/v1/token-prices-refresh?refresh=true&pages=2"

[[cron.jobs]]
name = "limit-order-executor-1min"
schedule = "*/1 * * * *"
endpoint = "/functions/v1/limit-order-executor"
