import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'sv' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation data
const translations = {
  sv: {
    // Site metadata
    'site.title': 'Crypto Network Sweden - Din Krypto Community | Bitcoin, Ethereum & DeFi',
    'site.description': 'Sveriges ledande krypto community. Lär dig om kryptovalutor, följ marknaden i realtid och träff nya vänner med samma passion för Web3. Gå med idag!',
    
    // Header & Navigation
    'nav.home': 'Hem',
    'nav.market': 'Marknad',
    'nav.portfolio': 'Portfolio',
    'nav.trading': 'Handel',
    'nav.memeZone': 'Meme Zone',
    'nav.createToken': 'Skapa Token',
    'nav.tools': 'Verktyg',
    'nav.news': 'Nyheter',
    'nav.community': 'Community',
    'nav.wallet': 'Plånbok',
    'nav.mainPages': 'Huvudsidor',
    
    // Descriptions
    'desc.home': 'Startsida',
    'desc.market': 'Marknadsöversikt',
    'desc.portfolio': 'Min portfolio & watchlist',
    'desc.trading': 'Trading & analys',
    'desc.memeZone': 'Meme coins & tokens',
    'desc.createToken': 'Skapa din egen token',
    'desc.tools': 'Krypto verktyg',
    'desc.news': 'Senaste nyheterna',
    'desc.community': 'Community & forum',
    
    // Portfolio Page
    'portfolio.title': 'Portfolio',
    'portfolio.overview': 'Översikt',
    'portfolio.holdings': 'Innehav',
    'portfolio.transactions': 'Transaktioner',
    'portfolio.watchlist': 'Watchlist',
    'portfolio.totalValue': 'Totalt värde',
    'portfolio.totalPnL': 'Totalt PnL',
    'portfolio.dayChange': 'Förändr. 24h',
    'portfolio.hideValues': 'Dölj värden',
    'portfolio.showValues': 'Visa värden',
    'portfolio.refresh': 'Uppdatera',
    'portfolio.noWallet': 'Ingen plånbok ansluten',
    'portfolio.connectWallet': 'Anslut en Solana-plånbok för att se din portfolio',
    'portfolio.error': 'Fel vid hämtning av portfoliodata',
    'portfolio.tryAgain': 'Försök igen om en stund',
    'portfolio.updated': 'Data uppdaterad',
    'portfolio.updateFailed': 'Kunde inte uppdatera data',
    'portfolio.connected': 'Ansluten',
    'portfolio.disconnected': 'Frånkopplad',
    
    // Market Overview Page
    'market.title': 'Marknadsöversikt',
    'market.description': 'Realtidsöversikt av kryptomarknaden',
    'market.search': 'Sök kryptovaluta...',
    'market.all': 'Alla',
    'market.gainers': 'Vinnare',
    'market.losers': 'Förlorare',
    'market.favorites': 'Favoriter',
    'market.name': 'Namn',
    'market.price': 'Pris',
    'market.change24h': '24h %',
    'market.volume': 'Volym',
    'market.marketCap': 'Marknadsvärde',
    'market.supply': 'Utbud',
    'market.rank': 'Rank',
    'market.loading': 'Laddar marknadsdata...',
    'market.error': 'Kunde inte ladda marknadsdata',
    'market.noResults': 'Inga resultat hittades',
    'market.addToWatchlist': 'Lägg till i watchlist',
    'market.removeFromWatchlist': 'Ta bort från watchlist',
    'market.viewChart': 'Visa diagram',
    'market.trade': 'Handla',
    'market.tableView': 'Tabellvy',
    'market.gridView': 'Rutnätsvy',
    'market.cryptocurrencies': 'Kryptovalutor',
    'market.showing': 'Visar',
    'market.of': 'av',
    'market.top10': 'TOP 10',
    'market.trending': 'Trending',
    'market.meme': 'Meme',
    'market.gainersShort': 'Toppar',
    'market.losersShort': 'Fallande',
    'market.allShort': 'Alla',
    'market.totalMarketCap': 'Total Market Cap',
    'market.fearGreed': 'Fear & Greed Index',
    'market.altSeason': 'Alt Season',
    'market.btcDominance': 'BTC Dominance',
    'market.volume24h': 'Volume 24h',
    'market.trading': 'Trading',
    'market.btcDom': 'BTC Dom',
    'market.btcSeason': 'BTC Season',
    'market.altSeasonIndex': 'Alt Season Index',
    'market.liveCryptoData': 'Live kryptodata och marknadsanalys',
    'market.aiMarketAnalysis': 'AI-MARKNADSANALYS',
    'market.loadingAI': 'Laddar AI-analys…',
    'market.aiSummaryUnavailable': 'AI sammanfattning otillgänglig just nu.',
    'market.positives': 'Positiva',
    'market.toWatch': 'Att Bevaka',
    'market.cap': 'Cap',
    'market.detailedInfo': 'Detaljerad info',
    'market.aiResearchInProgress': 'AI Research Pågår',
    'market.openAIAnalyzing': 'OpenAI researchmodellen analyserar marknaden...',
    'market.fetchingRealTimeData': 'Hämtar realtidsdata från 10+ källor',
    'market.analyzingTechnicalIndicators': 'Analyserar tekniska indikatorer (RSI, MACD, MA)',
    'market.calculatingSupportResistance': 'Beräknar exakta stöd- och motståndsnivåer',
    'market.identifyingBreakouts': 'Identifierar breakout/breakdown-möjligheter',
    'market.verifyingSentiment': 'Verifierar sentimentdata från sociala medier',
    'market.trend': 'Trend',
    'market.aiMarketAnalysisDefault': 'AI-marknadsanalys från OpenAI researchmodellen med realtidsdata',
    'market.analyzingPositiveSignals': 'Analyserar Positiva Signaler',
    'market.analyzingRiskFactors': 'Analyserar Riskfaktorer',
    'market.calculatingTechnicalLevels': 'Beräknar Tekniska Nivåer med Realtidsdata',
    'market.calculating': 'Beräknar...',
    'market.currentPrice': 'Aktuellt pris',
    'market.nextSupport': 'Nästa stöd',
    'market.nextResistance': 'Nästa motstånd',
    'market.positiveSignalsAI': 'Positiva Signaler (AI)',
    'market.noPositiveSignals': 'Inga starka positiva signaler just nu.',
    'market.toWatchAI': 'Att Bevaka (AI)',
    'market.noRiskFactors': 'Inga större riskfaktorer identifierade.',
    'market.technicalLevelsAI': 'Tekniska Nivåer (AI-Research med Realtidsdata)',
    'market.realtimeAI': 'Realtids AI',
    'market.technicalAnalysisAI': 'Teknisk Analys (AI-verifierad med webbsökning)',
    'market.aiVerified': 'AI-verifierad',
    'market.detailedAIResearch': 'Detaljerad AI-research',
    'market.lastUpdate': 'Senaste uppdatering',
    'market.sources': 'Källor',
    'market.topCryptocurrencies': 'Topp Kryptovalutor',
    'market.marketAnalysis': 'Marknadsanalys',
    
    
    // Hero Section
    'hero.title': 'Sveriges Krypto Community',
    'hero.subtitle': 'Lär dig, handla och väx med Sveriges ledande krypto-community',
    'hero.cta': 'Börja Nu',
    'hero.exploreMarket': 'Utforska Marknaden',
    'hero.livePrices': 'Live Priser',
    'hero.realTimeData': 'Realtidsdata',
    'hero.secureTrading': 'Säker Handel',
    
    // Meme Hero
    'meme.hero.title': 'HETASTE TOKENS',
    'meme.hero.subtitle': 'De 20 mest explosiva meme tokens just nu – Live data från marknaden',
    'meme.hero.liveUpdates': 'LIVE UPPDATERINGAR',
    'meme.hero.loading': 'Laddar hetaste tokens...',
    'meme.hero.tryAgain': 'Försök igen',
    'meme.hero.exploreAll': 'UTFORSKA ALLA TOKENS',
    'meme.hero.updates': 'Uppdateras varje minut',
    'meme.hero.hottestTokens': 'hetaste tokens',
    'meme.hero.explosive': 'EXPLOSIV',
    'meme.hero.hot': 'HET',
    'meme.hero.trending': 'TRENDING',
    'meme.hero.tradeNow': 'HANDLA NU',
    'meme.hero.price': 'PRIS',
    'meme.hero.mcap': 'MCAP',
    
    // Meme Pages
    'meme.buyToken.title': 'Köp Token',
    'meme.buyToken.description': 'Köp och sälj meme tokens med avancerad analys och realtidsdata',
    'meme.buyToken.searchPlaceholder': 'Sök token adress',
    'meme.buyToken.tokenFound': 'Token hittad',
    'meme.buyToken.fetchFailed': 'Misslyckades att hämta token',
    'meme.buyToken.checkAddress': 'Kontrollera adressen och försök igen.',
    'meme.buyToken.invalidAmount': 'Ogiltigt belopp',
    'meme.buyToken.enterValidAmount': 'Ange ett giltigt belopp att köpa för.',
    'meme.buyToken.buyInitiated': 'Köp initierat',
    'meme.buyToken.buyDescription': 'Öppnar wallet för att köpa',
    'meme.buyToken.sellInitiated': 'Sälj initierat',
    'meme.buyToken.sellDescription': 'Öppnar wallet för att sälja',
    'meme.buyToken.verified': 'Verified ✓',
    'meme.buyToken.unverified': 'Unverified',
    'meme.buyToken.info': 'Info',
    'meme.buyToken.chart': 'Diagram',
    'meme.buyToken.priceChart': 'Pris Chart',
    'meme.buyToken.infoTrade': 'Info & Handel',
    'meme.buyToken.liveData': 'Live Data',
    'meme.buyToken.technicalAnalysis': 'Technical Analysis',
    'meme.buyToken.realtimeData': 'Realtids data',
    'meme.buyToken.secureTrade': 'Säker handel',
    'meme.buyToken.advancedAnalysis': 'Avancerad analys',
    'meme.buyToken.risk': 'Risk',
    'meme.buyToken.low': 'Låg',
    'meme.buyToken.medium': 'Medium',
    'meme.buyToken.high': 'Hög',
    'meme.buyToken.marketCap': 'Market Cap',
    'meme.buyToken.holders': 'Holders',
    'meme.buyToken.volume24h': '24h Volume',
    'meme.buyToken.tokenInformation': 'Token Information',
    'meme.buyToken.totalSupply': 'Total Supply',
    'meme.buyToken.verifiedStatus': 'Verified',
    'meme.buyToken.contractAddress': 'Contract Address',
    'meme.buyToken.copied': 'Kopierad!',
    'meme.buyToken.copiedDescription': 'Contract address kopierad till urklipp.',
    'meme.buyToken.copy': 'Kopiera',
    'meme.buyToken.socialLinks': 'Sociala länkar',
    'meme.buyToken.trade': 'Handla',
    'meme.buyToken.amount': 'Belopp',
    'meme.buyToken.sol': 'SOL',
    'meme.buyToken.buyNow': 'Köp Nu',
    'meme.buyToken.sell': 'Sälj',
    'meme.buyToken.tradeNote': 'Handeln kommer att öppnas i din anslutna plånbok (Phantom, Solflare, etc.)',
    'meme.buyToken.advancedChart': 'Avancerat Chart',
    'meme.buyToken.tradingViewIntegration': 'TradingView integration kommer här',
    'meme.buyToken.realtimePriceData': 'Realtids prisdata och teknisk analys',
    'meme.buyToken.discoverTokens': 'Upptäck Meme Tokens',
    'meme.buyToken.discoverDescription': 'Använd sökfunktionen för att hitta och analysera meme tokens. Få detaljerad information, prisdata och handelsverktyg.',
    
    
    'meme.createToken.title': 'Skapa Meme Token',
    'meme.createToken.titleFull': 'Skapa Din Meme Token – Token Creator',
    'meme.createToken.description': 'Skapa din egen meme token med vår avancerade token creator. Ladda upp bilder, anpassa metadata och lansera din token på blockchain.',
    'meme.createToken.designDesc': 'Designa din egen meme cryptocurrency',
    'meme.createToken.beta': 'Beta',
    'meme.createToken.advancedCreator': 'Advanced Creator • Blockchain Ready',
    'meme.createToken.createYourOwn': 'Skapa Din Egen Meme Token',
    'meme.createToken.designAndPreview': 'Designa och förhandsgranska din meme cryptocurrency med professionella verktyg, anpassningsbara metadata och modern UI.',
    
    'meme.hub.title': 'Meme Zone Hub - Skapa, Handla & Analysera',
    'meme.hub.description': 'Komplett meme token ekosystem: Skapa egna tokens, handla säkert och få djupanalys av marknaden.',
    'meme.hub.createToken': 'Skapa Token',
    'meme.hub.createTokenDesc': 'Designa din egen meme cryptocurrency med professionella verktyg',
    'meme.hub.tradeTokens': 'Handla Tokens',
    'meme.hub.tradeTokensDesc': 'Köp och sälj meme tokens med avancerad marknadsanalys',
    'meme.hub.marketStats': 'Marknadsstatistik',
    'meme.hub.marketStatsDesc': 'Live data, trender och djupanalys av meme token marknaden',
    'meme.hub.tokenExplorer': 'Token Explorer',
    'meme.hub.tokenExplorerDesc': 'Utforska alla meme tokens med detaljerad information',
    'meme.hub.new': 'New',
    'meme.hub.beta': 'Beta',
    'meme.hub.live': 'Live',
    
    'meme.main.title': 'Meme Tokens – Ultimate Meme Coin Universe',
    'meme.main.description': 'Världens mest färgglada meme token-sida med stora bilder, live-data och interaktiv upplevelse. Upptäck de hetaste meme-coinsen nu!',
    
    'meme.stats.title': 'Meme Zone Statistik',
    'meme.stats.description': 'Live marknadsdata och trender',
    'meme.stats.live': 'Live',
    'meme.stats.marketCap': 'Market Cap',
    'meme.stats.activeTokens': 'Active Tokens',
    'meme.stats.volume24h': '24h Volume',
    'meme.stats.topGainer': 'Top Gainer',
    'meme.stats.topPerformers': 'Top Performers (24h)',
    'meme.stats.marketSentiment': 'Marknadssentiment',
    'meme.stats.bullishSentiment': 'Bullish Sentiment',
    'meme.stats.fearGreedIndex': 'Fear & Greed Index',
    'meme.stats.greed': 'Greed',
    'meme.stats.socialActivity': 'Social Activity',
    
    // Additional common translations needed
    'common.of': 'av',
    'common.and': 'och',
    'common.for': 'för',
    'common.last24h': 'senaste 24h',
    'common.premium': 'Premium',
    'common.today': 'idag',
    'common.members': 'Aktiva Medlemmar',
    'common.resources': 'Utbildningsresurser',
    'common.cryptocurrencies': 'Olika kryptovalutor',

    // Footer translations
    'footer.followUs': 'FÖLJ OSS PÅ SOCIALA MEDIER',
    'footer.riskWarning': 'Riskvarning:',
    'footer.riskDescription': 'Handel med kryptovalutor är förknippat med höga risker. Investeringar kan både öka och minska i värde. Investera aldrig mer än vad du har råd att förlora. Crypto Network Sweden tillhandahåller endast utbildningsinnehåll och är inte finansiell rådgivning.',
    'footer.privacyPolicy': 'Integritetspolicy',
    'footer.termsOfService': 'Användarvillkor',
    'footer.cookies': 'Cookies',

    // Mobile Navigation translations
    'mobileNav.home': 'Hem',
    'mobileNav.market': 'Marknad',
    'mobileNav.memeZone': 'Meme Zone',
    'mobileNav.trading': 'Handel',
    'mobileNav.news': 'Nyheter',


    // Crypto Detail Page translations
    'crypto.backToMarket': 'Tillbaka till Marknad',
    'crypto.watchlist': 'Bevakningslista',
    'crypto.priceChange': 'Prisförändring',
    'crypto.marketCap': 'Börsvärde', 
    'crypto.volume24h': '24h Volym',
    'crypto.supply': 'Utbud',
    'crypto.chart': 'Diagram',
    'crypto.orderbook': 'Orderbok',
    'crypto.trades': 'Affärer',
    'crypto.info': 'Info',
    'crypto.loading': 'Laddar...',
    'crypto.error': 'Fel vid laddning av data',
    'crypto.retry': 'Försök igen',
    
    'nav.price': 'Pris',
    
    // Trading
    'trading.buy': 'Köp',
    'trading.sell': 'Sälj',
    'trading.amount': 'Mängd',
    'trading.total': 'Totalt',
    'trading.orderBook': 'Orderbok',
    'trading.recentTrades': 'Senaste affärer',
    'trading.openOrders': 'Öppna order',
    'trading.orderHistory': 'Orderhistorik',
    'trading.balance': 'Saldo',
    'trading.available': 'Tillgängligt',
    'trading.chart': 'Diagram',
    'trading.analysis': 'Analys',
    'trading.market': 'Market',
    'trading.limit': 'Limit',
    'trading.stop': 'Stop',
    'trading.instant': 'Instant',
    'trading.target': 'Target',
    'trading.loss': 'Loss',
    'trading.amountSol': 'Mängd (SOL)',
    'trading.percentage': 'Procent (%)',
    'trading.customAmount': 'Anpassad mängd',
    'trading.targetPrice': 'Sätt ditt målpris',
    'trading.stopPrice': 'Sätt ditt stop loss pris',
    'trading.buyNow': 'Köp Nu',
    'trading.sellNow': 'Sälj Nu',
    'trading.slippage': 'Slippage',
    'trading.priority': 'Prioritet',
    'trading.low': 'Låg',
    'trading.medium': 'Medium',
    'trading.high': 'Hög',
    'trading.connectWallet': 'Anslut plånbok för handel',
    'trading.connectWalletToTrade': 'Anslut din plånbok för att börja handla',
    'trading.connectWalletDescription': 'Anslut din plånbok för att börja handla',
    'trading.positions': 'Positioner',
    'trading.walletBalances': 'Plånbok Saldo',
    'trading.orderValue': 'Ordervärde',
    'trading.fee': 'Avgift',
    'trading.price': 'Pris',
    'trading.noOpenOrders': 'Inga öppna ordrar',
    'trading.live': 'Live',
    'trading.offline': 'Offline',
    'trading.spread': 'Spread',
    'trading.high24h': '24h Hög',
    'trading.low24h': '24h Låg',
    'trading.volume': 'Volym',
    'trading.marketCap': 'Börsvärde',
    'trading.currentPrice': 'Aktuellt pris',
    'trading.orderType': 'Ordertyp',
    'trading.quickSelection': 'Snabbval (% av saldo)',
    'trading.feesInfo': 'Avgifter & Information',
    'trading.tradingFee': 'Trading fee',
    'trading.estimatedFees': 'Beräknade avgifter',
    'trading.youWillReceive': 'Du får ca',
    'trading.tradingWarning': 'Trading Warning',
    'trading.tradingWarningText': 'Cryptocurrency trading involves high risks and you may lose your entire invested capital. Trade only with funds you can afford to lose.',
    'trading.limitPrice': 'Limit Price',
    
    // News Section
    'news.title': 'Senaste Nyheterna',
    'news.readMore': 'Läs mer',
    'news.source': 'Källa',
    'news.published': 'Publicerad',
    'news.loading': 'Laddar nyheter...',
    'news.error': 'Kunde inte ladda nyheter',
    'news.noArticles': 'Inga artiklar hittades',
    
    // Community Section
    'community.title': 'Gå med i Communityn',
    'community.subtitle': 'Anslut dig till tusentals kryptoentusiaster',
    'community.discord': 'Discord Server',
    'community.telegram': 'Telegram Grupp',
    'community.twitter': 'Twitter Community',
    'community.youtube': 'YouTube Kanal',
    'community.join': 'Gå med',
    'community.members': 'medlemmar',
    'community.online': 'online',
    
    // Footer
    'footer.about': 'Om Oss',
    'footer.contact': 'Kontakt',
    'footer.terms': 'Villkor',
    'footer.privacy': 'Integritet',
    'footer.support': 'Support',
    'footer.api': 'API',
    'footer.blog': 'Blogg',
    'footer.careers': 'Karriär',
    'footer.copyright': '© 2024 Crypto Network Sweden. Alla rättigheter förbehållna.',
    
    // Tools Page
    'tools.title': 'Krypto Verktyg',
    'tools.calculator': 'Kalkylator',
    'tools.converter': 'Omvandlare',
    'tools.alerts': 'Prisvarningar',
    'tools.portfolio': 'Portfolio Tracker',
    'tools.news': 'Nyheter',
    'tools.calendar': 'Kalender',
    'tools.learn': 'Lär dig',
    'tools.dca': 'DCA Kalkylator',
    
    // Wallet
    'wallet.connect': 'Anslut Plånbok',
    'wallet.connected': 'Ansluten',
    'wallet.disconnect': 'Koppla från',
    'wallet.address': 'Adress',
    'wallet.balance': 'Saldo',
    'wallet.transactions': 'Transaktioner',
    'wallet.send': 'Skicka',
    'wallet.receive': 'Ta emot',
    'wallet.swap': 'Växla',
    // Common
    'common.loading': 'Laddar...',
    'common.error': 'Fel uppstod',
    'common.retry': 'Försök igen',
    'common.close': 'Stäng',
    'common.open': 'Öppna',
    'common.save': 'Spara',
    'common.cancel': 'Avbryt',
    'common.confirm': 'Bekräfta',
    'common.search': 'Sök',
    'common.filter': 'Filtrera',
    'common.sort': 'Sortera',
    'common.connect': 'Anslut',
    'common.connected': 'Ansluten',
    'common.disconnect': 'Koppla från',
    'common.view': 'Visa',
    'common.edit': 'Redigera',
    'common.delete': 'Ta bort',
    'common.add': 'Lägg till',
    'common.remove': 'Ta bort',
    'common.update': 'Uppdatera',
    'common.refresh': 'Uppdatera',
    'common.empty': 'tom',
    'common.comingSoon': 'kommer snart',
    'portfolio.startByAdding': 'Börja med att lägga till kryptovalutor genom att klicka på stjärnan',
    'portfolio.workingOnAdvanced': 'Vi arbetar på avancerade analysfunktioner för din portfolio',
    'common.back': 'Tillbaka',
    'common.next': 'Nästa',
    'common.previous': 'Föregående',
    'common.submit': 'Skicka',
    'common.reset': 'Återställ',
    'common.select': 'Välj',
    'common.copy': 'Kopiera',
    'common.share': 'Dela',
    'common.export': 'Exportera',
    'common.import': 'Importera',
    'common.download': 'Ladda ner',
    'common.upload': 'Ladda upp',
    'common.settings': 'Inställningar',
    'common.help': 'Hjälp',
    'common.about': 'Om',
    'common.contact': 'Kontakt',
    
    // Page-specific content
    'page.memeHub.centerTitle': 'Ditt centrum för meme token ekosystemet',
    'page.memeHub.ecosystem': 'Komplett Meme Token Ekosystem',
    'page.memeHub.createAnalyze': 'Skapa, Handla & Analysera',
    'page.memeHub.completeDescription': 'Allt du behöver för att delta i meme token revolutionen på ett ställe. Från skapande till handel och analys.',
    'page.memeHub.openAction': 'Öppna',
    'page.memeHub.activeTokens': 'Aktiva Tokens',
    'page.memeHub.totalTradingVolume': 'Total Handelsvolym',
    'page.memeHub.community': 'Community',
    'page.memeHub.createdTokens': 'Skapade Tokens',
    'page.memeHub.popularActions': 'Populära Aktioner',
    'page.memeHub.buyBonkToken': 'Köp BONK Token',
    'page.memeHub.createFirstToken': 'Skapa Min Första Token',
    'page.memeHub.viewMarketStats': 'Se Marknadsstatistik',
    
    // Crypto detail page
    'page.crypto.loadingCrypto': 'Laddar kryptovaluta data...',
    'page.crypto.loadingError': 'Fel vid laddning',
    'page.crypto.errorDescription': 'Det gick inte att ladda kryptodata. Kontrollera din internetanslutning och försök igen.',
    'page.crypto.tryAgain': 'Försök igen',
    'page.crypto.backToHomepage': 'Tillbaka till startsidan',
    'page.crypto.tokenNotFound': 'Token ej hittad',
    'page.crypto.tokenNotFoundDescription': 'Kryptovalutan finns inte tillgänglig eller har tagits bort från vårt system.',
    'page.crypto.searchOtherTokens': 'Sök andra tokens',
    'page.crypto.popularAlternatives': 'Populära alternativ:',
    
    // Token detail
    'page.token.backToMarket': 'Back to Market',
    'page.token.livePriceChart': 'Live Price Chart',
    'page.token.liveTrading': 'Live Trading',
    'page.token.loading': 'Loading token...',
    'page.token.invalidAmount': 'Ogiltigt belopp',
    'page.token.tradeFailed': 'Trade misslyckades',
    
    // ToolsPage translations
    'tools.page.title': 'VERKTYG',
    'tools.telegramBots': 'TELEGRAM BOTS',
    'tools.automateTrading': 'Automatisera din kryptohandel med våra kraftfulla Telegram bots',
    'tools.tradingBot.name': 'Trading Bot',
    'tools.tradingBot.description': 'Köp och sälj tokens blixtsnabbt direkt från Telegram. Automatiska order med smart routing för bästa priser.',
    'tools.tradingBot.features.fastTransactions': 'Snabba transaktioner',
    'tools.tradingBot.features.smartRouting': 'Smart routing',
    'tools.tradingBot.features.multiDEX': 'Multi-DEX support',
    'tools.tradingBot.features.walletIntegration': 'Säker wallet integration',
    'tools.tradingBot.price': 'Gratis att testa',
    'tools.snipeBot.name': 'Snipe Bot',
    'tools.snipeBot.description': 'Snipea nya token launches och få försprång på marknaden. Automatisk detektering av nya listings.',
    'tools.snipeBot.features.autoDetect': 'Auto-detect launches',
    'tools.snipeBot.features.mevProtection': 'MEV protection',
    'tools.snipeBot.features.gasOptimization': 'Gas optimization',
    'tools.snipeBot.features.instantExecution': 'Instant execution',
    'tools.snipeBot.price': 'Premium',
    'tools.priceAlertBot.name': 'Price Alert Bot',
    'tools.priceAlertBot.description': 'Få instant notifikationer när dina tokens når specifika prisnivåer. Aldrig missa en bra möjlighet igen.',
    'tools.priceAlertBot.features.customAlerts': 'Custom alerts',
    'tools.priceAlertBot.features.multiTokenTracking': 'Multi-token tracking',
    'tools.priceAlertBot.features.technicalIndicators': 'Technical indicators',
    'tools.priceAlertBot.features.portfolioMonitoring': 'Portfolio monitoring',
    'tools.priceAlertBot.price': 'Gratis',
    'tools.newsBot.name': 'Nyhets Bot',
    'tools.newsBot.description': 'Få de senaste krypto-nyheterna direkt till Telegram. AI-filtrerade nyheter baserat på dina intressen.',
    'tools.newsBot.features.aiFiltered': 'AI-filtrerade nyheter',
    'tools.newsBot.features.realTimeAlerts': 'Real-time alerts',
    'tools.newsBot.features.marketAnalysis': 'Market analysis',
    'tools.newsBot.features.socialSentiment': 'Social sentiment',
    'tools.portfolioBot.name': 'Portfolio Bot',
    'tools.portfolioBot.description': 'Spåra din portfolio i realtid med avancerad analys och insikter. Perfect för aktiva traders.',
    'tools.portfolioBot.features.realTimeTracking': 'Real-time tracking',
    'tools.portfolioBot.features.plAnalysis': 'P&L analysis',
    'tools.portfolioBot.features.riskManagement': 'Risk management',
    'tools.portfolioBot.features.taxReporting': 'Tax reporting',
    'tools.securityBot.name': 'Security Bot',
    'tools.securityBot.description': 'Skanna tokens för säkerhetsrisker innan du investerar. Skydda dig från rug pulls och scams.',
    'tools.securityBot.features.contractScanning': 'Contract scanning',
    'tools.securityBot.features.rugPullDetection': 'Rug pull detection',
    'tools.securityBot.features.teamVerification': 'Team verification',
    'tools.securityBot.features.riskScoring': 'Risk scoring',
    'tools.features.fastExecution': 'Blixtsnabb Execution',
    'tools.features.fastExecutionDesc': 'Våra bots är optimerade för hastighet och kan utföra trades på millisekunder',
    'tools.features.bankSecurity': 'Bank-nivå Säkerhet',
    'tools.features.bankSecurityDesc': 'All kommunikation är krypterad och vi lagrar aldrig dina privata nycklar',
    'tools.features.communityDriven': 'Community Driven',
    'tools.features.communityDrivenDesc': 'Över 50,000+ aktiva användare som förlitar sig på våra verktyg dagligen',
    'tools.features.support247': '24/7 Support',
    'tools.features.support247Desc': 'Vårt team är alltid tillgängligt för att hjälpa dig med dina frågor',
    'tools.hot': 'HOT',
    'tools.popular': 'POPULÄR',
    'tools.start': 'Starta',
    'tools.startBot': 'Starta Bot',
    'tools.buySellSolana': 'Köp/Sälj på Solana (Jupiter)',
    'tools.smoothSwap': 'Smidig swap via Jupiter DEX-aggregatorn',
    'tools.whyChoose': 'Varför Välja Våra Verktyg?',
    'tools.whyChooseDesc': 'Vi har byggt plattformen som traders behöver - snabb, säker och användarvänlig',
    'tools.activeUsers': 'Aktiva användare',
    'tools.uptime': 'Uptime',
    'tools.secureReliable': 'Säker & Pålitlig',
    'tools.readyToStart': 'Redo att Börja?',
    'tools.readyToStartDesc': 'Gå med i tusentals traders som redan använder våra verktyg',
    'tools.joinTelegram': 'Gå med i Telegram',
    'tools.exploreMarket': 'Utforska Marknaden',
    
    // NewsPage translations
    'news.page.title': 'CRYPTO NETWORK NYHETER',
    'news.page.description': 'Sveriges mest omfattande och aktuella källa för krypto-nyheter, marknadsanalys och branschinsikter.',
    'news.page.descriptionShort': 'Håll dig uppdaterad med realtidsrapportering från våra experter.',
    'news.liveUpdates': 'Live uppdateringar var 3:e minut',
    'news.expertAnalysis': 'Expertanalys från branschledare',
    'news.searchPlaceholder': 'Sök nyheter',
    'news.searchPlaceholderLong': 'Sök nyheter, författare eller taggar...',
    'news.backToHomepage': 'Tillbaka till startsidan',
    'news.filterBy': 'Datum',
    'news.filterByImpact': 'Påverkan',
    'news.categories.all': 'ALLA',
    'news.categories.btc': 'BTC',
    'news.categories.eth': 'ETH',
    'news.categories.memes': 'MEMES',
    'news.categories.politics': 'POLITIK',
    'news.categories.trending': 'TRENDING',
    'news.justNow': 'Just nu',
    'news.minutesAgo': 'min sedan',
    'news.hoursAgo': 'h sedan',
    'news.daysAgo': 'd sedan',
    'news.minRead': 'min läsning',
    'news.readMoreLink': 'Läs mer',
    'news.unknown': 'Okänd',
    'news.dailyReport': 'DAGLIG KRYPTO RAPPORT',
    'news.dailyReportDescription': 'Få de viktigaste kryptonotiserna levererade direkt via vår Telegram-community varje dag.',
    
    // Market translations
    'market.alert': 'MARKNADS ALERT',
    'market.fear': 'Rädsla',
    'market.greed': 'Girighet', 
    'market.neutral': 'Neutral',
    
    // CommunityPage translations  
    'community.page.title': 'VÅR COMMUNITY',
    'community.page.subtitle': 'Sveriges största krypto-community',
    'community.page.description': 'Anslut till vår växande Telegram-community. Ställ frågor, lär dig, tradea tillsammans och hitta nya möjligheter - helt gratis!',
    'community.joinNowFree': 'Gå med nu - Gratis!',
    'community.memberCount': 'medlemmar',
    'community.rating': 'rating',
    'community.telegramCommunity.title': 'Telegram Community',
    'community.telegramCommunity.description': 'Öppen grupp för alla krypto-entusiaster',
    'community.telegramCommunity.count': '5,000+ medlemmar',
    'community.voiceChat.title': 'Voice Chat Trading',
    'community.voiceChat.description': 'Trade tillsammans i realtid',
    'community.voiceChat.count': 'Dagligen 20:00',
    'community.memeScanning.title': 'Meme Token Scanning',
    'community.memeScanning.description': 'Hitta nästa stora möjlighet',
    'community.memeScanning.count': '24/7 aktiv',
    'community.newFriends.title': 'Nya Vänner',
    'community.newFriends.description': 'Träffa likasinnade personer',
    'community.newFriends.count': 'Alltid välkommen',
    'community.ongoingActivities': 'PÅGÅENDE AKTIVITETER',
    'community.ongoingActivitiesDesc': 'Delta i våra regelbundna community-aktiviteter',
    'community.events.voiceChat': 'Voice Chat Trading',
    'community.events.voiceChatTime': 'Dagligen 20:00',
    'community.events.voiceChatParticipants': '50-100 personer',
    'community.events.voiceChatType': 'Live Trading',
    'community.events.memeScanning': 'Meme Token Scanning',
    'community.events.memeScanningTime': '24/7 aktiv',
    'community.events.memeScanningParticipants': 'Community driven',
    'community.events.memeScanningType': 'Token Discovery',
    'community.events.qa': 'Frågor & Svar',
    'community.events.qaTime': 'Alltid öppet',
    'community.events.qaParticipants': 'Alla välkomna',
    'community.events.qaType': 'Support',
    'community.whatMembersSay': 'VAD SÄGER VÅRA MEDLEMMAR',
    'community.testimonial1.name': 'Anna L.',
    'community.testimonial1.role': 'Community Medlem',
    'community.testimonial1.content': 'Bästa Telegram-gruppen! Alla hjälper varandra och vi tradear tillsammans.',
    'community.testimonial1.time': '8 månader',
    'community.testimonial2.name': 'Erik M.',
    'community.testimonial2.role': 'Meme Token Hunter',
    'community.testimonial2.content': 'Vi scannar meme tokens tillsammans varje dag! Gruppen har hjälpt mig hitta många gems.',
    'community.testimonial2.time': '1 år',
    'community.testimonial3.name': 'Maria S.',
    'community.testimonial3.role': 'Voice Chat Regular',
    'community.testimonial3.content': 'Voice chat sessionerna är fantastiska! Träffat så många nya vänner.',
    'community.testimonial3.time': '6 månader',
    'community.readyToJoin': 'REDO ATT GÅ MED?',
    'community.readyToJoinDesc': 'Anslut till tusentals andra krypto-entusiaster och ta din trading till nästa nivå',
    'community.joinTelegramCommunity': 'Gå med i Telegram Community',
    'common.support': 'Support',
    'common.more': 'Mer',
    'common.less': 'Mindre',
    'common.show': 'Visa',
    'common.hide': 'Dölj',
    'common.expand': 'Expandera',
    'common.collapse': 'Kollapsa',
    'common.yes': 'Ja',
    'common.no': 'Nej',
    'common.ok': 'OK',
    'common.continue': 'Fortsätt',
    'common.finish': 'Slutför',
    'common.start': 'Starta',
    'common.stop': 'Stoppa',
    'common.pause': 'Pausa',
    'common.play': 'Spela',
    'common.record': 'Spela in',
    'common.live': 'Live',
    'common.offline': 'Offline',
    'common.online': 'Online',
    'common.public': 'Offentlig',
    'common.private': 'Privat',
    'common.enabled': 'Aktiverad',
    'common.disabled': 'Inaktiverad',
    'common.active': 'Aktiv',
    'common.inactive': 'Inaktiv',
    'common.new': 'Ny',
    'common.old': 'Gammal',
    'common.latest': 'Senaste',
    'common.oldest': 'Äldsta',
    'common.popular': 'Populär',
    'common.trending': 'Trending',
    'common.featured': 'Utvald',
    'common.recommended': 'Rekommenderad',

    // Meme Zone-specifika översättningar
    'memeZone.title': 'Meme Zone',
    'memeZone.discoverTokens': 'Upptäck hetaste tokens',
    'memeZone.activeTokens': 'Aktiva Tokens',
    'memeZone.avgGain24h': 'Snitt Vinst 24h',
    'memeZone.totalVolume': 'Total Volym',
    'memeZone.trending': 'Trendande',
    'memeZone.new': 'Nya',
    'memeZone.gainers': 'Vinnare',
    'memeZone.volume': 'Volym',
    'memeZone.grid': 'Rutnät',
    'memeZone.lista': 'Lista',
    'memeZone.buyNow': 'KÖP NU',
    'memeZone.hot': 'HET',
    'memeZone.topGainer': 'TOPP',
    'memeZone.marketOverview': 'Marknadsöversikt',
    'memeZone.live': 'Live',
    'memeZone.marketSentiment': 'Marknadssentiment',
    'memeZone.extremelyBullish': 'Extremt Bullish',
    'memeZone.bullBearRatio': 'Tjur/Björn Ratio',
    'memeZone.bear': 'Björn',
    'memeZone.bull': 'Tjur',
    'memeZone.home': 'Hem',
    'memeZone.create': 'Skapa',
    'memeZone.portfolio': 'Portfolio',
    'memeZone.searchTokens': 'Sök tokens...',
    'memeZone.recentSearches': 'Senaste sökningar',
    'memeZone.trendingNow': 'Trendande nu',
    'memeZone.searchResults': 'Sökresultat för',
    'memeZone.noResults': 'Inga resultat för',
    'memeZone.cancel': 'Avbryt',
    'memeZone.previous': 'Föregående',
    'memeZone.next': 'Nästa',
    'memeZone.page': 'Sida',
    'memeZone.of': 'av',
    'memeZone.tokensTotal': 'tokens totalt',
    'memeZone.refreshed': 'Senast uppdaterad',

    // Creator-specifika översättningar
    'memeCreator.title': 'SKAPA DIN MEME TOKEN',
    'memeCreator.tokenName': 'TOKEN NAMN',
    'memeCreator.symbol': 'SYMBOL',
    'memeCreator.totalSupply': 'TOTAL SUPPLY',
    'memeCreator.locked': 'LÅST',
    'memeCreator.supplyNote': 'Supply är fastställd på 1 miljard tokens',
    'memeCreator.description': 'BESKRIVNING',
    'memeCreator.socialLinks': 'SOCIALA LÄNKAR',
    'memeCreator.twitter': 'TWITTER',
    'memeCreator.website': 'HEMSIDA',
    'memeCreator.telegram': 'TELEGRAM',
    'memeCreator.tokenImage': 'TOKEN BILD',
    'memeCreator.uploadImage': 'LADDA UPP EGEN BILD',
    'memeCreator.disclaimer': 'Obs: Detta är en visuell prototyp utan blockchain-deploy. Använd för att designa och planera din token innan lansering.',
    'memeCreator.livePreview': 'LIVE FÖRHANDSVISNING',
    'memeCreator.ready': 'REDO',
    'memeCreator.forLaunch': 'FÖR LANSERING',
    'memeCreator.socialLinksPreview': 'SOCIALA LÄNKAR',
    'memeCreator.status': 'STATUS',

    // Hero-specifika översättningar
    'memeHero.activeTokens': 'Aktiva Tokens',
    'memeHero.avgGain24h': 'Snitt Vinst 24h',
    'memeHero.totalVolume': 'Total Volym',

    // Search-specifika översättningar
    'memeSearch.searchTokens': 'Sök tokens...',
    'memeSearch.recentSearches': 'Senaste sökningar',
    'memeSearch.trendingNow': 'Trendande nu',
    'memeSearch.searchResults': 'Sökresultat för',
    'memeSearch.noResults': 'Inga resultat för',
    'memeSearch.cancel': 'Avbryt',
    'memeSearch.hot': 'HET',

    // Stats-specifika översättningar  
    'memeStats.marketCap': 'Market Cap',
    'memeStats.totalVolume': 'Total Volume',
    'memeStats.activeTraders': 'Active Traders',
    'memeStats.hotTokens': 'Hot Tokens',
    'memeStats.marketOverview': 'Marknadsöversikt',
    'memeStats.live': 'Live',
    'memeStats.marketSentiment': 'Marknadssentiment',
    'memeStats.extremelyBullish': 'Extremt Bullish',
    'memeStats.bullBearRatio': 'Tjur/Björn Ratio',
    'memeStats.bear': 'Björn',
    'memeStats.bull': 'Tjur',
    'memeStats.topPerformers': 'Topp Prestationer (24h)',
    'memeStats.bullishSentiment': 'Bullish Sentiment',
    'memeStats.fearGreedIndex': 'Fear & Greed Index',
    'memeStats.greed': 'Girighet',
    'memeStats.socialActivity': 'Social Aktivitet',

    // Pagination-specifika översättningar
    'memePagination.previous': 'Föregående',
    'memePagination.next': 'Nästa',
    'memePagination.page': 'Sida',
    'memePagination.of': 'av',
    'memePagination.tokensTotal': 'tokens totalt',

    // Zone Tabs-specifika översättningar
    'memeZoneTabs.tokenExplorer': 'TOKEN EXPLORER',
    'memeZoneTabs.discoverTokens': 'UPPTÄCK TOKENS',
    'memeZoneTabs.exploreDescription': 'Utforska alla meme tokens med avancerade filter och sortering',
    'memeZoneTabs.categories': 'Kategorier',
    'memeZoneTabs.sort': 'Sortera',
    'memeZoneTabs.view': 'Vy',
    'memeZoneTabs.grid': 'Rutnät',
    'memeZoneTabs.list': 'Lista',
    'memeZoneTabs.trending': 'Trending',
    'memeZoneTabs.gainers': 'Gainers',
    'memeZoneTabs.marketCapHigh': 'Market Cap High',
    'memeZoneTabs.marketCapLow': 'Market Cap Low',
    'memeZoneTabs.volume': 'Volume',
    'memeZoneTabs.newest': 'Newest',
    'memeZoneTabs.marketCap': 'Market Cap',
    'memeZoneTabs.volume24h': 'Volume 24h',
    'memeZoneTabs.change24h': '24h Change',
    'memeZoneTabs.holders': 'Holders',
    'memeZoneTabs.price': 'Price',
    'memeZoneTabs.tryAgain': 'Försök igen',
    'memeZoneTabs.tradeNow': 'HANDLA NU',
    'memeZoneTabs.previous': 'Föregående',
    'memeZoneTabs.next': 'Nästa',
    'memeZoneTabs.page': 'Sida',

    // Trading page translations
    'trading.desktop.overview': 'Handelsöversikt',
    'trading.desktop.stats': 'Handelsstatistik',
    'trading.desktop.totalVolume': 'Total Volym',
    'trading.desktop.openOrders': 'Öppna Order',
    'trading.desktop.avgDailyVolume': 'Snitt Daglig Volym',
    'trading.desktop.priceAlerts': 'Prisvarningar',
    'trading.desktop.marketDepth': 'Marknadsdjup',
    'trading.desktop.buyOrders': 'Köporder',
    'trading.desktop.sellOrders': 'Säljorder',
    'trading.desktop.spread': 'Spread',
    'trading.desktop.orders': 'Order',
    'trading.desktop.positions': 'Positioner',
    'trading.desktop.history': 'Historik',
    'trading.desktop.smartTrade': 'Smart Handel',
    'trading.desktop.wallet': 'Plånbok',
    'trading.desktop.connectWalletToTrade': 'Anslut din plånbok för att börja handla BTC',
    'trading.desktop.selectWallet': 'Välj Plånbok',
    'trading.desktop.marketAnalysis': 'Marknadsanalys',
    'trading.desktop.technical': 'Teknisk',
    'trading.desktop.analysis': 'Analys',
    'trading.desktop.sentiment': 'Sentiment',
    'trading.desktop.rsi': 'RSI',
    'trading.desktop.macd': 'MACD',
    'trading.desktop.sma': 'SMA',
    'trading.desktop.ema': 'EMA',
    'trading.desktop.bullish': 'Bullish',
    'trading.desktop.neutral': 'Neutral',
    'trading.desktop.bearish': 'Bearish',
    'trading.desktop.buySignal': 'Köpsignal',
    'trading.desktop.sellSignal': 'Säljsignal',
    'trading.desktop.holdSignal': 'Håll Signal',
    'trading.desktop.tradeNow': 'Handla Nu',
    'trading.desktop.buy': 'Köp',
    'trading.desktop.sell': 'Sälj',
    'trading.desktop.amount': 'Mängd',
    'trading.desktop.price': 'Pris',
    'trading.desktop.total': 'Totalt',
    'trading.desktop.market': 'Market',
    'trading.desktop.limit': 'Limit',
    'trading.desktop.stop': 'Stop',
    'trading.desktop.placeOrder': 'Lägg Order',
    'trading.desktop.orderType': 'Ordertyp',
    'trading.desktop.orderForm': 'Orderformulär',

    'trading.mobile.overview': 'Översikt',
    'trading.mobile.stats': 'Statistik',
    'trading.mobile.orders': 'Order',
    'trading.mobile.history': 'Historik',
    'trading.mobile.wallet': 'Plånbok',
    'trading.mobile.trade': 'Handla',
    'trading.mobile.buy': 'Köp',
    'trading.mobile.sell': 'Sälj',
    'trading.mobile.amount': 'Mängd',
    'trading.mobile.price': 'Pris',
    'trading.mobile.total': 'Totalt',
    'trading.mobile.balance': 'Saldo',
    'trading.mobile.available': 'Tillgängligt',
    'trading.mobile.market': 'Market',
    'trading.mobile.limit': 'Limit',
    'trading.mobile.placeOrder': 'Lägg Order',
    'trading.mobile.connectWallet': 'Anslut Plånbok',
    'trading.mobile.selectWallet': 'Välj Plånbok',
    'trading.mobile.walletConnected': 'Plånbok Ansluten',
    'trading.mobile.disconnect': 'Koppla från',
    'trading.mobile.connectToTrade': 'Anslut din plånbok för att börja handla',
    'trading.mobile.portfolio': 'Portfolio',
    'trading.mobile.noOpenOrders': 'Inga öppna order',
    'trading.mobile.noOrderHistory': 'Ingen orderhistorik',
    'trading.mobile.lastPrice': 'Senaste Pris',
    'trading.mobile.change24h': '24h Förändring',
    'trading.mobile.volume24h': '24h Volym',
    'trading.mobile.high24h': '24h Högsta',
    'trading.mobile.low24h': '24h Lägsta'
  },
  en: {
    // Site metadata
    'site.title': 'Crypto Network Sweden - Your Crypto Community | Bitcoin, Ethereum & DeFi',
    'site.description': 'Sweden\'s leading crypto community. Learn about cryptocurrencies, follow the market in real-time and meet new friends with the same passion for Web3. Join today!',
    
    // Header & Navigation
    'nav.home': 'Home',
    'nav.market': 'Market',
    'nav.portfolio': 'Portfolio',
    'nav.trading': 'Trading',
    'nav.memeZone': 'Meme Zone',
    'nav.createToken': 'Create Token',
    'nav.tools': 'Tools',
    'nav.news': 'News',
    'nav.community': 'Community',
    'nav.wallet': 'Wallet',
    'nav.mainPages': 'Main Pages',
    
    // Descriptions
    'desc.home': 'Homepage',
    'desc.market': 'Market overview',
    'desc.portfolio': 'My portfolio & watchlist',
    'desc.trading': 'Trading & analysis',
    'desc.memeZone': 'Meme coins & tokens',
    'desc.createToken': 'Create your own token',
    'desc.tools': 'Crypto tools',
    'desc.news': 'Latest news',
    'desc.community': 'Community & forum',
    
    // Portfolio Page
    'portfolio.title': 'Portfolio',
    'portfolio.overview': 'Overview',
    'portfolio.holdings': 'Holdings',
    'portfolio.transactions': 'Transactions',
    'portfolio.watchlist': 'Watchlist',
    'portfolio.totalValue': 'Total Value',
    'portfolio.totalPnL': 'Total PnL',
    'portfolio.dayChange': '24h Change',
    'portfolio.hideValues': 'Hide Values',
    'portfolio.showValues': 'Show Values',
    'portfolio.refresh': 'Refresh',
    'portfolio.noWallet': 'No wallet connected',
    'portfolio.connectWallet': 'Connect a Solana wallet to view your portfolio',
    'portfolio.error': 'Error fetching portfolio data',
    'portfolio.tryAgain': 'Try again in a moment',
    'portfolio.updated': 'Data updated',
    'portfolio.updateFailed': 'Could not update data',
    'portfolio.connected': 'Connected',
    'portfolio.disconnected': 'Disconnected',
    
    // Market Overview Page
    'market.title': 'Market Overview',
    'market.description': 'Real-time overview of the crypto market',
    'market.search': 'Search cryptocurrency...',
    'market.all': 'All',
    'market.gainers': 'Gainers',
    'market.losers': 'Losers',
    'market.favorites': 'Favorites',
    'market.name': 'Name',
    'market.price': 'Price',
    'market.change24h': '24h %',
    'market.volume': 'Volume',
    'market.marketCap': 'Market Cap',
    'market.supply': 'Supply',
    'market.rank': 'Rank',
    'market.loading': 'Loading market data...',
    'market.error': 'Could not load market data',
    'market.noResults': 'No results found',
    'market.addToWatchlist': 'Add to watchlist',
    'market.removeFromWatchlist': 'Remove from watchlist',
    'market.viewChart': 'View chart',
    'market.trade': 'Trade',
    'market.tableView': 'Table view',
    'market.gridView': 'Grid view',
    'market.cryptocurrencies': 'Cryptocurrencies',
    'market.showing': 'Showing',
    'market.of': 'of',
    'market.top10': 'TOP 10',
    'market.trending': 'Trending',
    'market.meme': 'Meme',
    'market.gainersShort': 'Gainers',
    'market.losersShort': 'Losers',
    'market.allShort': 'All',
    'market.totalMarketCap': 'Total Market Cap',
    'market.fearGreed': 'Fear & Greed Index',
    'market.altSeason': 'Alt Season',
    'market.btcDominance': 'BTC Dominance',
    'market.volume24h': 'Volume 24h',
    'market.trading': 'Trading',
    'market.btcDom': 'BTC Dom',
    'market.btcSeason': 'BTC Season',
    'market.altSeasonIndex': 'Alt Season Index',
    'market.liveCryptoData': 'Live crypto data and market analysis',
    'market.aiMarketAnalysis': 'AI MARKET ANALYSIS',
    'market.loadingAI': 'Loading AI analysis…',
    'market.aiSummaryUnavailable': 'AI summary unavailable right now.',
    'market.positives': 'Positives',
    'market.toWatch': 'To Watch',
    'market.cap': 'Cap',
    'market.detailedInfo': 'Detailed info',
    'market.aiResearchInProgress': 'AI Research In Progress',
    'market.openAIAnalyzing': 'OpenAI research model analyzing the market...',
    'market.fetchingRealTimeData': 'Fetching real-time data from 10+ sources',
    'market.analyzingTechnicalIndicators': 'Analyzing technical indicators (RSI, MACD, MA)',
    'market.calculatingSupportResistance': 'Calculating exact support and resistance levels',
    'market.identifyingBreakouts': 'Identifying breakout/breakdown opportunities',
    'market.verifyingSentiment': 'Verifying sentiment data from social media',
    'market.trend': 'Trend',
    'market.aiMarketAnalysisDefault': 'AI market analysis from OpenAI research model with real-time data',
    'market.analyzingPositiveSignals': 'Analyzing Positive Signals',
    'market.analyzingRiskFactors': 'Analyzing Risk Factors',
    'market.calculatingTechnicalLevels': 'Calculating Technical Levels with Real-time Data',
    'market.calculating': 'Calculating...',
    'market.currentPrice': 'Current price',
    'market.nextSupport': 'Next support',
    'market.nextResistance': 'Next resistance',
    'market.positiveSignalsAI': 'Positive Signals (AI)',
    'market.noPositiveSignals': 'No strong positive signals right now.',
    'market.toWatchAI': 'To Watch (AI)',
    'market.noRiskFactors': 'No major risk factors identified.',
    'market.technicalLevelsAI': 'Technical Levels (AI-Research with Real-time Data)',
    'market.realtimeAI': 'Real-time AI',
    'market.technicalAnalysisAI': 'Technical Analysis (AI-verified with web search)',
    'market.aiVerified': 'AI-verified',
    'market.detailedAIResearch': 'Detailed AI research',
    'market.lastUpdate': 'Last update',
    'market.sources': 'Sources',
    'market.sentimentAnalysis': 'Sentiment Analysis',
    'market.socialMedia': 'Social Media',
    'market.institutionalFlow': 'Institutional Flow',
    'market.technicalAnalysis': 'Technical Analysis',
    'market.topCryptocurrencies': 'Top Cryptocurrencies',
    'market.marketAnalysis': 'Market Analysis',
    
    // Hero Section
    'hero.title': 'Sweden\'s Crypto Community',
    'hero.subtitle': 'Learn, trade and grow with Sweden\'s leading crypto community',
    'hero.cta': 'Get Started',
    'hero.exploreMarket': 'Explore Market',
    'hero.livePrices': 'Live Prices',
    'hero.realTimeData': 'Real-time Data',
    'hero.secureTrading': 'Secure Trading',
    
    // Meme Hero
    'meme.hero.title': 'HOTTEST TOKENS',
    'meme.hero.subtitle': 'The 20 most explosive meme tokens right now – Live market data',
    'meme.hero.liveUpdates': 'LIVE UPDATES',
    'meme.hero.loading': 'Loading hottest tokens...',
    'meme.hero.tryAgain': 'Try Again',
    'meme.hero.exploreAll': 'EXPLORE ALL TOKENS',
    'meme.hero.updates': 'Updates every minute',
    'meme.hero.hottestTokens': 'hottest tokens',
    'meme.hero.explosive': 'EXPLOSIVE',
    'meme.hero.hot': 'HOT',
    'meme.hero.trending': 'TRENDING',
    'meme.hero.tradeNow': 'TRADE NOW',
    'meme.hero.price': 'PRICE',
    'meme.hero.mcap': 'MCAP',
    
    
    // Meme Stats Page
    'memeStatsPage.title': 'Meme Zone Statistics',
    'memeStatsPage.description': 'Live market data and trends',
    'memeStatsPage.live': 'Live',
    'memeStatsPage.marketCap': 'Market Cap',
    'memeStatsPage.activeTokens': 'Active Tokens',
    'memeStatsPage.volume24h': '24h Volume',
    'memeStatsPage.topGainer': 'Top Gainer',
    'memeStatsPage.topPerformers': 'Top Performers (24h)',
    'memeStatsPage.marketSentiment': 'Market Sentiment',
    'memeStatsPage.bullishSentiment': 'Bullish Sentiment',
    'memeStatsPage.fearGreedIndex': 'Fear & Greed Index',
    'memeStatsPage.greed': 'Greed',
    'memeStatsPage.socialActivity': 'Social Activity',

    // Meme Pages
    'meme.buyToken.title': 'Buy Token',
    'meme.buyToken.description': 'Buy and sell meme tokens with advanced analysis and real-time data',
    'meme.buyToken.searchPlaceholder': 'Search token address',
    'meme.buyToken.tokenFound': 'Token found',
    'meme.buyToken.fetchFailed': 'Failed to fetch token',
    'meme.buyToken.checkAddress': 'Check the address and try again.',
    'meme.buyToken.invalidAmount': 'Invalid amount',
    'meme.buyToken.enterValidAmount': 'Enter a valid amount to buy.',
    'meme.buyToken.buyInitiated': 'Buy initiated',
    'meme.buyToken.buyDescription': 'Opening wallet to buy',
    'meme.buyToken.sellInitiated': 'Sell initiated',
    'meme.buyToken.sellDescription': 'Opening wallet to sell',
    'meme.buyToken.verified': 'Verified ✓',
    'meme.buyToken.unverified': 'Unverified',
    'meme.buyToken.info': 'Info',
    'meme.buyToken.chart': 'Chart',
    'meme.buyToken.priceChart': 'Price Chart',
    'meme.buyToken.infoTrade': 'Info & Trade',
    'meme.buyToken.liveData': 'Live Data',
    'meme.buyToken.technicalAnalysis': 'Technical Analysis',
    'meme.buyToken.realtimeData': 'Real-time data',
    'meme.buyToken.secureTrade': 'Secure trading',
    'meme.buyToken.advancedAnalysis': 'Advanced analysis',
    'meme.buyToken.risk': 'Risk',
    'meme.buyToken.low': 'Low',
    'meme.buyToken.medium': 'Medium',
    'meme.buyToken.high': 'High',
    'meme.buyToken.marketCap': 'Market Cap',
    'meme.buyToken.holders': 'Holders',
    'meme.buyToken.volume24h': '24h Volume',
    'meme.buyToken.tokenInformation': 'Token Information',
    'meme.buyToken.totalSupply': 'Total Supply',
    'meme.buyToken.verifiedStatus': 'Verified',
    'meme.buyToken.contractAddress': 'Contract Address',
    'meme.buyToken.copied': 'Copied!',
    'meme.buyToken.copiedDescription': 'Contract address copied to clipboard.',
    'meme.buyToken.copy': 'Copy',
    'meme.buyToken.socialLinks': 'Social Links',
    'meme.buyToken.trade': 'Trade',
    'meme.buyToken.amount': 'Amount',
    'meme.buyToken.sol': 'SOL',
    'meme.buyToken.buyNow': 'Buy Now',
    'meme.buyToken.sell': 'Sell',
    'meme.buyToken.tradeNote': 'Trading will open in your connected wallet (Phantom, Solflare, etc.)',
    'meme.buyToken.advancedChart': 'Advanced Chart',
    'meme.buyToken.tradingViewIntegration': 'TradingView integration coming here',
    'meme.buyToken.realtimePriceData': 'Real-time price data and technical analysis',
    'meme.buyToken.discoverTokens': 'Discover Meme Tokens',
    'meme.buyToken.discoverDescription': 'Use the search function to find and analyze meme tokens. Get detailed information, price data and trading tools.',
    
    
    'meme.createToken.title': 'Create Meme Token',
    'meme.createToken.titleFull': 'Create Your Meme Token – Token Creator',
    'meme.createToken.description': 'Create your own meme token with our advanced token creator. Upload images, customize metadata and launch your token on blockchain.',
    'meme.createToken.designDesc': 'Design your own meme cryptocurrency',
    'meme.createToken.beta': 'Beta',
    'meme.createToken.advancedCreator': 'Advanced Creator • Blockchain Ready',
    'meme.createToken.createYourOwn': 'Create Your Own Meme Token',
    'meme.createToken.designAndPreview': 'Design and preview your meme cryptocurrency with professional tools, customizable metadata and modern UI.',
    
    'meme.hub.title': 'Meme Zone Hub - Create, Trade & Analyze',
    'meme.hub.description': 'Complete meme token ecosystem: Create your own tokens, trade safely and get in-depth market analysis.',
    'meme.hub.createToken': 'Create Token',
    'meme.hub.createTokenDesc': 'Design your own meme cryptocurrency with professional tools',
    'meme.hub.tradeTokens': 'Trade Tokens',
    'meme.hub.tradeTokensDesc': 'Buy and sell meme tokens with advanced market analysis',
    'meme.hub.marketStats': 'Market Statistics',
    'meme.hub.marketStatsDesc': 'Live data, trends and in-depth analysis of the meme token market',
    'meme.hub.tokenExplorer': 'Token Explorer',
    'meme.hub.tokenExplorerDesc': 'Explore all meme tokens with detailed information',
    'meme.hub.new': 'New',
    'meme.hub.beta': 'Beta',
    'meme.hub.live': 'Live',
    
    'meme.main.title': 'Meme Tokens – Ultimate Meme Coin Universe',
    'meme.main.description': 'The world\'s most colorful meme token page with large images, live data and interactive experience. Discover the hottest meme coins now!',
    
    'meme.stats.title': 'Meme Zone Statistics',
    'meme.stats.description': 'Live market data and trends',
    'meme.stats.live': 'Live',
    'meme.stats.marketCap': 'Market Cap',
    'meme.stats.activeTokens': 'Active Tokens',
    'meme.stats.volume24h': '24h Volume',
    'meme.stats.topGainer': 'Top Gainer',
    'meme.stats.topPerformers': 'Top Performers (24h)',
    'meme.stats.marketSentiment': 'Market Sentiment',
    'meme.stats.bullishSentiment': 'Bullish Sentiment',
    'meme.stats.fearGreedIndex': 'Fear & Greed Index',
    'meme.stats.greed': 'Greed',
    'meme.stats.socialActivity': 'Social Activity',
    
    // Additional common translations needed
    'common.of': 'of',
    'common.and': 'and',
    'common.for': 'for',
    'common.last24h': 'last 24h',
    'common.premium': 'Premium',
    'common.today': 'today',
    'common.members': 'Active Members',
    'common.resources': 'Educational Resources',
    'common.cryptocurrencies': 'Different cryptocurrencies',

    // Footer translations
    'footer.followUs': 'FOLLOW US ON SOCIAL MEDIA',
    'footer.riskWarning': 'Risk Warning:',
    'footer.riskDescription': 'Trading cryptocurrencies involves high risks. Investments can both increase and decrease in value. Never invest more than you can afford to lose. Crypto Network Sweden provides only educational content and is not financial advice.',
    'footer.privacyPolicy': 'Privacy Policy',
    'footer.termsOfService': 'Terms of Service',
    'footer.cookies': 'Cookies',

    // Mobile Navigation translations
    'mobileNav.home': 'Home',
    'mobileNav.market': 'Market',
    'mobileNav.memeZone': 'Meme Zone',
    'mobileNav.trading': 'Trading',
    'mobileNav.news': 'News',


    // Crypto Detail Page translations
    'crypto.backToMarket': 'Back to Market',
    'crypto.watchlist': 'Watchlist',
    'crypto.priceChange': 'Price Change',
    'crypto.marketCap': 'Market Cap', 
    'crypto.volume24h': '24h Volume',
    'crypto.supply': 'Supply',
    'crypto.chart': 'Chart',
    'crypto.orderbook': 'Order Book',
    'crypto.trades': 'Trades',
    'crypto.info': 'Info',
    'crypto.loading': 'Loading...',
    'crypto.error': 'Error loading data',
    'crypto.retry': 'Try again',
    
    'nav.price': 'Price',
    
     // Trading
    'trading.buy': 'Buy',
    'trading.sell': 'Sell',
    'trading.amount': 'Amount',
    'trading.total': 'Total',
    'trading.orderBook': 'Order Book',
    'trading.recentTrades': 'Recent Trades',
    'trading.openOrders': 'Open Orders',
    'trading.orderHistory': 'Order History',
    'trading.balance': 'Balance',
    'trading.available': 'Available',
    'trading.chart': 'Chart',
    'trading.analysis': 'Analysis',
    'trading.market': 'Market',
    'trading.limit': 'Limit',
    'trading.stop': 'Stop',
    'trading.instant': 'Instant',
    'trading.target': 'Target',
    'trading.loss': 'Loss',
    'trading.amountSol': 'Amount (SOL)',
    'trading.percentage': 'Percentage (%)',
    'trading.customAmount': 'Custom amount',
    'trading.targetPrice': 'Set your target price',
    'trading.stopPrice': 'Set your stop loss price',
    'trading.buyNow': 'Buy Now',
    'trading.sellNow': 'Sell Now',
    'trading.slippage': 'Slippage',
    'trading.priority': 'Priority',
    'trading.low': 'Low',
    'trading.medium': 'Medium',
    'trading.high': 'High',
    'trading.connectWallet': 'Connect wallet to trade',
    'trading.connectWalletToTrade': 'Connect your wallet to start trading',
    'trading.connectWalletDescription': 'Connect your wallet to start trading',
    'trading.positions': 'Positions',
    'trading.walletBalances': 'Wallet Balances',
    'trading.orderValue': 'Order Value',
    'trading.fee': 'Fee',
    'trading.price': 'Price',
    'trading.noOpenOrders': 'No open orders',
    'trading.live': 'Live',
    'trading.offline': 'Offline',
    'trading.spread': 'Spread',
    'trading.high24h': '24h High',
    'trading.low24h': '24h Low',
    'trading.volume': 'Volume',
    'trading.marketCap': 'Market Cap',
    'trading.currentPrice': 'Current price',
    'trading.orderType': 'Order Type',
    'trading.quickSelection': 'Quick selection (% of balance)',
    'trading.feesInfo': 'Fees & Information',
    'trading.tradingFee': 'Trading fee',
    'trading.estimatedFees': 'Estimated fees',
    'trading.youWillReceive': 'You will receive approx',
    'trading.tradingWarning': 'Trading Warning',
    'trading.tradingWarningText': 'Cryptocurrency trading involves high risks and you may lose your entire invested capital. Trade only with funds you can afford to lose.',
    'trading.limitPrice': 'Limit Price',
    // News Section
    'news.title': 'Latest News',
    'news.readMore': 'Read more',
    'news.source': 'Source',
    'news.published': 'Published',
    'news.loading': 'Loading news...',
    'news.error': 'Could not load news',
    'news.noArticles': 'No articles found',
    
    // Community Section
    'community.title': 'Join the Community',
    'community.subtitle': 'Connect with thousands of crypto enthusiasts',
    'community.discord': 'Discord Server',
    'community.telegram': 'Telegram Group',
    'community.twitter': 'Twitter Community',
    'community.youtube': 'YouTube Channel',
    'community.join': 'Join',
    'community.members': 'members',
    'community.online': 'online',
    
    // Footer
    'footer.about': 'About Us',
    'footer.contact': 'Contact',
    'footer.terms': 'Terms',
    'footer.privacy': 'Privacy',
    'footer.support': 'Support',
    'footer.api': 'API',
    'footer.blog': 'Blog',
    'footer.careers': 'Careers',
    'footer.copyright': '© 2024 Crypto Network Sweden. All rights reserved.',
    
    // Tools Page
    'tools.title': 'Crypto Tools',
    'tools.calculator': 'Calculator',
    'tools.converter': 'Converter',
    'tools.alerts': 'Price Alerts',
    'tools.portfolio': 'Portfolio Tracker',
    'tools.news': 'News',
    'tools.calendar': 'Calendar',
    'tools.learn': 'Learn',
    'tools.dca': 'DCA Calculator',
    
    
    // Wallet
    'wallet.connect': 'Connect Wallet',
    'wallet.connected': 'Connected',
    'wallet.disconnect': 'Disconnect',
    'wallet.address': 'Address',
    'wallet.balance': 'Balance',
    'wallet.transactions': 'Transactions',
    'wallet.send': 'Send',
    'wallet.receive': 'Receive',
    'wallet.swap': 'Swap',
    
    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error occurred',
    'common.retry': 'Try again',
    'common.close': 'Close',
    'common.open': 'Open',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.confirm': 'Confirm',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.sort': 'Sort',
    'common.connect': 'Connect',
    'common.connected': 'Connected',
    'common.disconnect': 'Disconnect',
    'common.view': 'View',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.add': 'Add',
    'common.remove': 'Remove',
    'common.update': 'Update',
    'common.refresh': 'Refresh',
    'common.empty': 'empty',
    'common.comingSoon': 'coming soon',
    'portfolio.startByAdding': 'Start by adding cryptocurrencies by clicking on the star',
    'portfolio.workingOnAdvanced': 'We are working on advanced analytics features for your portfolio',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.submit': 'Submit',
    'common.reset': 'Reset',
    'common.select': 'Select',
    'common.copy': 'Copy',
    'common.share': 'Share',
    'common.export': 'Export',
    'common.import': 'Import',
    'common.download': 'Download',
    'common.upload': 'Upload',
    'common.settings': 'Settings',
    'common.help': 'Help',
    'common.about': 'About',
    'common.contact': 'Contact',
    
    // Page-specific content
    'page.memeHub.centerTitle': 'Your center for meme token ecosystem',
    'page.memeHub.ecosystem': 'Complete Meme Token Ecosystem',
    'page.memeHub.createAnalyze': 'Create, Trade & Analyze',
    'page.memeHub.completeDescription': 'Everything you need to participate in the meme token revolution in one place. From creation to trading and analysis.',
    'page.memeHub.openAction': 'Open',
    'page.memeHub.activeTokens': 'Active Tokens',
    'page.memeHub.totalTradingVolume': 'Total Trading Volume',
    'page.memeHub.community': 'Community',
    'page.memeHub.createdTokens': 'Created Tokens',
    'page.memeHub.popularActions': 'Popular Actions',
    'page.memeHub.buyBonkToken': 'Buy BONK Token',
    'page.memeHub.createFirstToken': 'Create My First Token',
    'page.memeHub.viewMarketStats': 'View Market Statistics',
    
    // Crypto detail page
    'page.crypto.loadingCrypto': 'Loading cryptocurrency data...',
    'page.crypto.loadingError': 'Loading Error',
    'page.crypto.errorDescription': 'Failed to load crypto data. Check your internet connection and try again.',
    'page.crypto.tryAgain': 'Try Again',
    'page.crypto.backToHomepage': 'Back to Homepage',
    'page.crypto.tokenNotFound': 'Token Not Found',
    'page.crypto.tokenNotFoundDescription': 'The cryptocurrency is not available or has been removed from our system.',
    'page.crypto.searchOtherTokens': 'Search Other Tokens',
    'page.crypto.popularAlternatives': 'Popular Alternatives:',
    
    // Token detail
    'page.token.backToMarket': 'Back to Market',
    'page.token.livePriceChart': 'Live Price Chart',
    'page.token.liveTrading': 'Live Trading',
    'page.token.loading': 'Loading token...',
    'page.token.invalidAmount': 'Invalid Amount',
    'page.token.tradeFailed': 'Trade Failed',
    
    // ToolsPage translations
    'tools.page.title': 'TOOLS',
    'tools.telegramBots': 'TELEGRAM BOTS',
    'tools.automateTrading': 'Automate your crypto trading with our powerful Telegram bots',
    'tools.tradingBot.name': 'Trading Bot',
    'tools.tradingBot.description': 'Buy and sell tokens lightning fast directly from Telegram. Automatic orders with smart routing for best prices.',
    'tools.tradingBot.features.fastTransactions': 'Fast transactions',
    'tools.tradingBot.features.smartRouting': 'Smart routing',
    'tools.tradingBot.features.multiDEX': 'Multi-DEX support',
    'tools.tradingBot.features.walletIntegration': 'Secure wallet integration',
    'tools.tradingBot.price': 'Free to try',
    'tools.snipeBot.name': 'Snipe Bot',
    'tools.snipeBot.description': 'Snipe new token launches and get ahead of the market. Automatic detection of new listings.',
    'tools.snipeBot.features.autoDetect': 'Auto-detect launches',
    'tools.snipeBot.features.mevProtection': 'MEV protection',
    'tools.snipeBot.features.gasOptimization': 'Gas optimization',
    'tools.snipeBot.features.instantExecution': 'Instant execution',
    'tools.snipeBot.price': 'Premium',
    'tools.priceAlertBot.name': 'Price Alert Bot',
    'tools.priceAlertBot.description': 'Get instant notifications when your tokens reach specific price levels. Never miss a good opportunity again.',
    'tools.priceAlertBot.features.customAlerts': 'Custom alerts',
    'tools.priceAlertBot.features.multiTokenTracking': 'Multi-token tracking',
    'tools.priceAlertBot.features.technicalIndicators': 'Technical indicators',
    'tools.priceAlertBot.features.portfolioMonitoring': 'Portfolio monitoring',
    'tools.priceAlertBot.price': 'Free',
    'tools.newsBot.name': 'News Bot',
    'tools.newsBot.description': 'Get the latest crypto news directly to Telegram. AI-filtered news based on your interests.',
    'tools.newsBot.features.aiFiltered': 'AI-filtered news',
    'tools.newsBot.features.realTimeAlerts': 'Real-time alerts',
    'tools.newsBot.features.marketAnalysis': 'Market analysis',
    'tools.newsBot.features.socialSentiment': 'Social sentiment',
    'tools.portfolioBot.name': 'Portfolio Bot',
    'tools.portfolioBot.description': 'Track your portfolio in real-time with advanced analysis and insights. Perfect for active traders.',
    'tools.portfolioBot.features.realTimeTracking': 'Real-time tracking',
    'tools.portfolioBot.features.plAnalysis': 'P&L analysis',
    'tools.portfolioBot.features.riskManagement': 'Risk management',
    'tools.portfolioBot.features.taxReporting': 'Tax reporting',
    'tools.securityBot.name': 'Security Bot',
    'tools.securityBot.description': 'Scan tokens for security risks before you invest. Protect yourself from rug pulls and scams.',
    'tools.securityBot.features.contractScanning': 'Contract scanning',
    'tools.securityBot.features.rugPullDetection': 'Rug pull detection',
    'tools.securityBot.features.teamVerification': 'Team verification',
    'tools.securityBot.features.riskScoring': 'Risk scoring',
    'tools.features.fastExecution': 'Lightning Fast Execution',
    'tools.features.fastExecutionDesc': 'Our bots are optimized for speed and can execute trades in milliseconds',
    'tools.features.bankSecurity': 'Bank-level Security',
    'tools.features.bankSecurityDesc': 'All communication is encrypted and we never store your private keys',
    'tools.features.communityDriven': 'Community Driven',
    'tools.features.communityDrivenDesc': 'Over 50,000+ active users rely on our tools daily',
    'tools.features.support247': '24/7 Support',
    'tools.features.support247Desc': 'Our team is always available to help you with your questions',
    'tools.hot': 'HOT',
    'tools.popular': 'POPULAR',
    'tools.start': 'Start',
    'tools.startBot': 'Start Bot',
    'tools.buySellSolana': 'Buy/Sell on Solana (Jupiter)',
    'tools.smoothSwap': 'Smooth swap via Jupiter DEX aggregator',
    'tools.whyChoose': 'Why Choose Our Tools?',
    'tools.whyChooseDesc': 'We built the platform traders need - fast, secure and user-friendly',
    'tools.activeUsers': 'Active users',
    'tools.uptime': 'Uptime',
    'tools.secureReliable': 'Secure & Reliable',
    'tools.readyToStart': 'Ready to Get Started?',
    'tools.readyToStartDesc': 'Join thousands of traders already using our tools',
    'tools.joinTelegram': 'Join Telegram',
    'tools.exploreMarket': 'Explore Market',
    
    // NewsPage translations
    'news.page.title': 'CRYPTO NETWORK NEWS',
    'news.page.description': 'Sweden\'s most comprehensive and current source for crypto news, market analysis and industry insights.',
    'news.page.descriptionShort': 'Stay updated with real-time reporting from our experts.',
    'news.liveUpdates': 'Live updates every 3 minutes',
    'news.expertAnalysis': 'Expert analysis from industry leaders',
    'news.searchPlaceholder': 'Search news',
    'news.searchPlaceholderLong': 'Search news, authors or tags...',
    'news.backToHomepage': 'Back to homepage',
    'news.filterBy': 'Date',
    'news.filterByImpact': 'Impact',
    'news.categories.all': 'ALL',
    'news.categories.btc': 'BTC',
    'news.categories.eth': 'ETH',
    'news.categories.memes': 'MEMES',
    'news.categories.politics': 'POLITICS',
    'news.categories.trending': 'TRENDING',
    'news.justNow': 'Just now',
    'news.minutesAgo': 'min ago',
    'news.hoursAgo': 'h ago',
    'news.daysAgo': 'd ago',
    'news.minRead': 'min read',
    'news.readMoreLink': 'Read more',
    'news.unknown': 'Unknown',
    
    // CommunityPage translations  
    'community.page.title': 'OUR COMMUNITY',
    'community.page.subtitle': 'Sweden\'s largest crypto community',
    'community.page.description': 'Join our growing Telegram community. Ask questions, learn, trade together and find new opportunities - completely free!',
    'community.joinNowFree': 'Join now - Free!',
    'community.memberCount': 'members',
    'community.rating': 'rating',
    'community.telegramCommunity.title': 'Telegram Community',
    'community.telegramCommunity.description': 'Open group for all crypto enthusiasts',
    'community.telegramCommunity.count': '5,000+ members',
    'community.voiceChat.title': 'Voice Chat Trading',
    'community.voiceChat.description': 'Trade together in real-time',
    'community.voiceChat.count': 'Daily 8:00 PM',
    'community.memeScanning.title': 'Meme Token Scanning',
    'community.memeScanning.description': 'Find the next big opportunity',
    'community.memeScanning.count': '24/7 active',
    'community.newFriends.title': 'New Friends',
    'community.newFriends.description': 'Meet like-minded people',
    'community.newFriends.count': 'Always welcome',
    'community.ongoingActivities': 'ONGOING ACTIVITIES',
    'community.ongoingActivitiesDesc': 'Participate in our regular community activities',
    'community.events.voiceChat': 'Voice Chat Trading',
    'community.events.voiceChatTime': 'Daily 8:00 PM',
    'community.events.voiceChatParticipants': '50-100 people',
    'community.events.voiceChatType': 'Live Trading',
    'community.events.memeScanning': 'Meme Token Scanning',
    'community.events.memeScanningTime': '24/7 active',
    'community.events.memeScanningParticipants': 'Community driven',
    'community.events.memeScanningType': 'Token Discovery',
    'community.events.qa': 'Q&A',
    'community.events.qaTime': 'Always open',
    'community.events.qaParticipants': 'Everyone welcome',
    'community.events.qaType': 'Support',
    'community.whatMembersSay': 'WHAT OUR MEMBERS SAY',
    'community.testimonial1.name': 'Anna L.',
    'community.testimonial1.role': 'Community Member',
    'community.testimonial1.content': 'Best Telegram group! Everyone helps each other and we trade together.',
    'community.testimonial1.time': '8 months',
    'community.testimonial2.name': 'Erik M.',
    'community.testimonial2.role': 'Meme Token Hunter',
    'community.testimonial2.content': 'We scan meme tokens together every day! The group has helped me find many gems.',
    'community.testimonial2.time': '1 year',
    'community.testimonial3.name': 'Maria S.',
    'community.testimonial3.role': 'Voice Chat Regular',
    'community.testimonial3.content': 'Voice chat sessions are fantastic! Met so many new friends.',
    'community.testimonial3.time': '6 months',
    'community.readyToJoin': 'READY TO JOIN?',
    'community.readyToJoinDesc': 'Connect with thousands of other crypto enthusiasts and take your trading to the next level',
    'community.joinTelegramCommunity': 'Join Telegram Community',
    'common.support': 'Support',
    'common.more': 'More',
    'common.less': 'Less',
    'common.show': 'Show',
    'common.hide': 'Hide',
    'common.expand': 'Expand',
    'common.collapse': 'Collapse',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.ok': 'OK',
    'common.continue': 'Continue',
    'common.finish': 'Finish',
    'common.start': 'Start',
    'common.stop': 'Stop',
    'common.pause': 'Pause',
    'common.play': 'Play',
    'common.record': 'Record',
    'common.live': 'Live',
    'common.offline': 'Offline',
    'common.online': 'Online',
    'common.public': 'Public',
    'common.private': 'Private',
    'common.enabled': 'Enabled',
    'common.disabled': 'Disabled',
    'common.active': 'Active',
    'common.inactive': 'Inactive',
    'common.new': 'New',
    'common.old': 'Old',
    'common.latest': 'Latest',
    'common.oldest': 'Oldest',
    'common.popular': 'Popular',
    'common.trending': 'Trending',
    'common.featured': 'Featured',
    'common.recommended': 'Recommended',

    // Meme Zone translations
    'memeZone.title': 'Meme Zone',
    'memeZone.discoverTokens': 'Discover the hottest tokens',
    'memeZone.activeTokens': 'Active Tokens',
    'memeZone.avgGain24h': 'Avg Gain 24h',
    'memeZone.totalVolume': 'Total Volume',
    'memeZone.trending': 'Trending',
    'memeZone.new': 'New',
    'memeZone.gainers': 'Gainers',
    'memeZone.volume': 'Volume',
    'memeZone.grid': 'Grid',
    'memeZone.lista': 'List',
    'memeZone.buyNow': 'BUY NOW',
    'memeZone.hot': 'HOT',
    'memeZone.topGainer': 'TOP GAINER',
    'memeZone.marketOverview': 'Market Overview',
    'memeZone.live': 'Live',
    'memeZone.marketSentiment': 'Market Sentiment',
    'memeZone.extremelyBullish': 'Extremely Bullish',
    'memeZone.bullBearRatio': 'Bull/Bear Ratio',
    'memeZone.bear': 'Bear',
    'memeZone.bull': 'Bull',
    'memeZone.home': 'Home',
    'memeZone.create': 'Create',
    'memeZone.portfolio': 'Portfolio',
    'memeZone.searchTokens': 'Search for tokens...',
    'memeZone.recentSearches': 'Recent searches',
    'memeZone.trendingNow': 'Trending now',
    'memeZone.searchResults': 'Search results for',
    'memeZone.noResults': 'No results for',
    'memeZone.cancel': 'Cancel',
    'memeZone.previous': 'Previous',
    'memeZone.next': 'Next',
    'memeZone.page': 'Page',
    'memeZone.of': 'of',
    'memeZone.tokensTotal': 'tokens total',
    'memeZone.refreshed': 'Last updated',

    // Creator-specific translations
    'memeCreator.title': 'CREATE YOUR MEME TOKEN',
    'memeCreator.tokenName': 'TOKEN NAME',
    'memeCreator.symbol': 'SYMBOL',
    'memeCreator.totalSupply': 'TOTAL SUPPLY',
    'memeCreator.locked': 'LOCKED',
    'memeCreator.supplyNote': 'Supply is fixed at 1 billion tokens',
    'memeCreator.description': 'DESCRIPTION',
    'memeCreator.socialLinks': 'SOCIAL LINKS',
    'memeCreator.twitter': 'TWITTER',
    'memeCreator.website': 'WEBSITE',
    'memeCreator.telegram': 'TELEGRAM',
    'memeCreator.tokenImage': 'TOKEN IMAGE',
    'memeCreator.uploadImage': 'UPLOAD CUSTOM IMAGE',
    'memeCreator.disclaimer': 'Note: This is a visual prototype without blockchain deployment. Use to design and plan your token before launch.',
    'memeCreator.livePreview': 'LIVE PREVIEW',
    'memeCreator.ready': 'READY',
    'memeCreator.forLaunch': 'FOR LAUNCH',
    'memeCreator.socialLinksPreview': 'SOCIAL LINKS',
    'memeCreator.status': 'STATUS',

    // Hero-specific translations
    'memeHero.activeTokens': 'Active Tokens',
    'memeHero.avgGain24h': 'Avg Gain 24h',
    'memeHero.totalVolume': 'Total Volume',

    // Search-specific translations
    'memeSearch.searchTokens': 'Search for tokens...',
    'memeSearch.recentSearches': 'Recent searches',
    'memeSearch.trendingNow': 'Trending now',
    'memeSearch.searchResults': 'Search results for',
    'memeSearch.noResults': 'No results for',
    'memeSearch.cancel': 'Cancel',
    'memeSearch.hot': 'HOT',

    // Stats-specific translations
    'memeStats.marketCap': 'Market Cap',
    'memeStats.totalVolume': 'Total Volume',
    'memeStats.activeTraders': 'Active Traders',
    'memeStats.hotTokens': 'Hot Tokens',
    'memeStats.marketOverview': 'Market Overview',
    'memeStats.live': 'Live',
    'memeStats.marketSentiment': 'Market Sentiment',
    'memeStats.extremelyBullish': 'Extremely Bullish',
    'memeStats.bullBearRatio': 'Bull/Bear Ratio',
    'memeStats.bear': 'Bear',
    'memeStats.bull': 'Bull',
    'memeStats.topPerformers': 'Top Performers (24h)',
    'memeStats.bullishSentiment': 'Bullish Sentiment',
    'memeStats.fearGreedIndex': 'Fear & Greed Index',
    'memeStats.greed': 'Greed',
    'memeStats.socialActivity': 'Social Activity',

    // Pagination-specific translations
    'memePagination.previous': 'Previous',
    'memePagination.next': 'Next',
    'memePagination.page': 'Page',
    'memePagination.of': 'of',
    'memePagination.tokensTotal': 'tokens total',

    // Zone Tabs-specific translations
    'memeZoneTabs.tokenExplorer': 'TOKEN EXPLORER',
    'memeZoneTabs.discoverTokens': 'DISCOVER TOKENS',
    'memeZoneTabs.exploreDescription': 'Explore all meme tokens with advanced filters and sorting',
    'memeZoneTabs.categories': 'Categories',
    'memeZoneTabs.sort': 'Sort',
    'memeZoneTabs.view': 'View',
    'memeZoneTabs.grid': 'Grid',
    'memeZoneTabs.list': 'List',
    'memeZoneTabs.trending': 'Trending',
    'memeZoneTabs.gainers': 'Gainers',
    'memeZoneTabs.marketCapHigh': 'Market Cap High',
    'memeZoneTabs.marketCapLow': 'Market Cap Low',
    'memeZoneTabs.volume': 'Volume',
    'memeZoneTabs.newest': 'Newest',
    'memeZoneTabs.marketCap': 'Market Cap',
    'memeZoneTabs.volume24h': 'Volume 24h',
    'memeZoneTabs.change24h': '24h Change',
    'memeZoneTabs.holders': 'Holders',
    'memeZoneTabs.price': 'Price',
    'memeZoneTabs.tryAgain': 'Try again',
    'memeZoneTabs.tradeNow': 'TRADE NOW',
    'memeZoneTabs.previousPage': 'Previous',
    'memeZoneTabs.nextPage': 'Next',
    'memeZoneTabs.page': 'Page',
    'memeZoneTabs.priceLabel': 'PRICE',
    'memeZoneTabs.mcapLabel': 'MCAP',
    'memeZoneTabs.vol24hLabel': '24H VOL',
    'memeZoneTabs.holdersLabel': 'HOLDERS',

    // Trading page translations
    'trading.desktop.overview': 'Trading Overview',
    'trading.desktop.stats': 'Trading Statistics',
    'trading.desktop.totalVolume': 'Total Volume',
    'trading.desktop.openOrders': 'Open Orders',
    'trading.desktop.avgDailyVolume': 'Avg Daily Volume',
    'trading.desktop.priceAlerts': 'Price Alerts',
    'trading.desktop.marketDepth': 'Market Depth',
    'trading.desktop.buyOrders': 'Buy Orders',
    'trading.desktop.sellOrders': 'Sell Orders',
    'trading.desktop.spread': 'Spread',
    'trading.desktop.orders': 'Orders',
    'trading.desktop.positions': 'Positions',
    'trading.desktop.history': 'History',
    'trading.desktop.smartTrade': 'Smart Trade',
    'trading.desktop.wallet': 'Wallet',
    'trading.desktop.connectWalletToTrade': 'Connect your wallet to start trading BTC',
    'trading.desktop.selectWallet': 'Select Wallet',
    'trading.desktop.marketAnalysis': 'Market Analysis',
    'trading.desktop.technical': 'Technical',
    'trading.desktop.analysis': 'Analysis',
    'trading.desktop.sentiment': 'Sentiment',
    'trading.desktop.rsi': 'RSI',
    'trading.desktop.macd': 'MACD',
    'trading.desktop.sma': 'SMA',
    'trading.desktop.ema': 'EMA',
    'trading.desktop.bullish': 'Bullish',
    'trading.desktop.neutral': 'Neutral',
    'trading.desktop.bearish': 'Bearish',
    'trading.desktop.buySignal': 'Buy Signal',
    'trading.desktop.sellSignal': 'Sell Signal',
    'trading.desktop.holdSignal': 'Hold Signal',
    'trading.desktop.tradeNow': 'Trade Now',
    'trading.desktop.buy': 'Buy',
    'trading.desktop.sell': 'Sell',
    'trading.desktop.amount': 'Amount',
    'trading.desktop.price': 'Price',
    'trading.desktop.total': 'Total',
    'trading.desktop.market': 'Market',
    'trading.desktop.limit': 'Limit',
    'trading.desktop.stop': 'Stop',
    'trading.desktop.placeOrder': 'Place Order',
    'trading.desktop.orderType': 'Order Type',
    'trading.desktop.orderForm': 'Order Form',

    'trading.mobile.overview': 'Overview',
    'trading.mobile.stats': 'Stats',
    'trading.mobile.orders': 'Orders',
    'trading.mobile.history': 'History',
    'trading.mobile.wallet': 'Wallet',
    'trading.mobile.trade': 'Trade',
    'trading.mobile.buy': 'Buy',
    'trading.mobile.sell': 'Sell',
    'trading.mobile.amount': 'Amount',
    'trading.mobile.price': 'Price',
    'trading.mobile.total': 'Total',
    'trading.mobile.balance': 'Balance',
    'trading.mobile.available': 'Available',
    'trading.mobile.market': 'Market',
    'trading.mobile.limit': 'Limit',
    'trading.mobile.placeOrder': 'Place Order',
    'trading.mobile.connectWallet': 'Connect Wallet',
    'trading.mobile.selectWallet': 'Select Wallet',
    'trading.mobile.walletConnected': 'Wallet Connected',
    'trading.mobile.disconnect': 'Disconnect',
    'trading.mobile.connectToTrade': 'Connect your wallet to start trading',
    'trading.mobile.portfolio': 'Portfolio',
    'trading.mobile.noOpenOrders': 'No open orders',
    'trading.mobile.noOrderHistory': 'No order history',
    'trading.mobile.lastPrice': 'Last Price',
    'trading.mobile.change24h': '24h Change',
    'trading.mobile.volume24h': '24h Volume',
    'trading.mobile.high24h': '24h High',
    'trading.mobile.low24h': '24h Low'
  }
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'sv';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  const value = {
    language,
    setLanguage,
    t
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};