import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'sv' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation data
const translations = {
  sv: {
    // Site metadata
    'site.title': 'Crypto Network Sweden - Din Krypto Community | Bitcoin, Ethereum & DeFi',
    'site.description': 'Sveriges ledande krypto community. Lär dig om kryptovalutor, följ marknaden i realtid och träff nya vänner med samma passion för Web3. Gå med idag!',
    
    // Header & Navigation
    'nav.home': 'Hem',
    'nav.market': 'Marknad',
    'nav.portfolio': 'Portfolio',
    'nav.trading': 'Handel',
    'nav.memeZone': 'Meme Zone',
    'nav.createToken': 'Skapa Token',
    'nav.tools': 'Verktyg',
    'nav.news': 'Nyheter',
    'nav.community': 'Community',
    'nav.wallet': 'Plånbok',
    'nav.mainPages': 'Huvudsidor',
    
    // Descriptions
    'desc.home': 'Startsida',
    'desc.market': 'Marknadsöversikt',
    'desc.portfolio': 'Min portfolio & watchlist',
    'desc.trading': 'Trading & analys',
    'desc.memeZone': 'Meme coins & tokens',
    'desc.createToken': 'Skapa din egen token',
    'desc.tools': 'Krypto verktyg',
    'desc.news': 'Senaste nyheterna',
    'desc.community': 'Community & forum',
    
    // Portfolio Page
    'portfolio.title': 'Portfolio',
    'portfolio.overview': 'Översikt',
    'portfolio.holdings': 'Innehav',
    'portfolio.transactions': 'Transaktioner',
    'portfolio.watchlist': 'Watchlist',
    'portfolio.totalValue': 'Totalt värde',
    'portfolio.totalPnL': 'Totalt PnL',
    'portfolio.dayChange': 'Förändr. 24h',
    'portfolio.hideValues': 'Dölj värden',
    'portfolio.showValues': 'Visa värden',
    'portfolio.refresh': 'Uppdatera',
    'portfolio.noWallet': 'Ingen plånbok ansluten',
    'portfolio.connectWallet': 'Anslut en Solana-plånbok för att se din portfolio',
    'portfolio.error': 'Fel vid hämtning av portfoliodata',
    'portfolio.tryAgain': 'Försök igen om en stund',
    'portfolio.updated': 'Data uppdaterad',
    'portfolio.updateFailed': 'Kunde inte uppdatera data',
    'portfolio.connected': 'Ansluten',
    'portfolio.disconnected': 'Frånkopplad',
    
    // Market Overview Page
    'market.title': 'Marknadsöversikt',
    'market.description': 'Realtidsöversikt av kryptomarknaden',
    'market.search': 'Sök kryptovaluta...',
    'market.all': 'Alla',
    'market.gainers': 'Vinnare',
    'market.losers': 'Förlorare',
    'market.favorites': 'Favoriter',
    'market.name': 'Namn',
    'market.price': 'Pris',
    'market.change24h': '24h %',
    'market.volume': 'Volym',
    'market.marketCap': 'Marknadsvärde',
    'market.supply': 'Utbud',
    'market.rank': 'Rank',
    'market.loading': 'Laddar marknadsdata...',
    'market.error': 'Kunde inte ladda marknadsdata',
    'market.noResults': 'Inga resultat hittades',
    'market.addToWatchlist': 'Lägg till i watchlist',
    'market.removeFromWatchlist': 'Ta bort från watchlist',
    'market.viewChart': 'Visa diagram',
    'market.trade': 'Handla',
    'market.tableView': 'Tabellvy',
    'market.gridView': 'Rutnätsvy',
    'market.cryptocurrencies': 'Kryptovalutor',
    'market.showing': 'Visar',
    'market.of': 'av',
    'market.top10': 'TOP 10',
    'market.trending': 'Trending',
    'market.meme': 'Meme',
    'market.gainersShort': 'Toppar',
    'market.losersShort': 'Fallande',
    'market.allShort': 'Alla',
    'market.totalMarketCap': 'Total Market Cap',
    'market.fearGreed': 'Fear & Greed Index',
    'market.altSeason': 'Alt Season',
    'market.btcDominance': 'BTC Dominance',
    'market.volume24h': 'Volume 24h',
    'market.trading': 'Trading',
    'market.btcDom': 'BTC Dom',
    'market.btcSeason': 'BTC Season',
    'market.altSeasonIndex': 'Alt Season Index',
    'market.liveCryptoData': 'Live kryptodata och marknadsanalys',
    
    // Hero Section
    'hero.title': 'Sveriges Krypto Community',
    'hero.subtitle': 'Lär dig, handla och väx med Sveriges ledande krypto-community',
    'hero.cta': 'Börja Nu',
    'hero.exploreMarket': 'Utforska Marknaden',
    'hero.livePrices': 'Live Priser',
    'hero.realTimeData': 'Realtidsdata',
    'hero.secureTrading': 'Säker Handel',
    
    // Meme Hero
    'meme.hero.title': 'HETASTE TOKENS',
    'meme.hero.subtitle': 'De 20 mest explosiva meme tokens just nu – Live data från marknaden',
    'meme.hero.liveUpdates': 'LIVE UPPDATERINGAR',
    'meme.hero.loading': 'Laddar hetaste tokens...',
    'meme.hero.tryAgain': 'Försök igen',
    'meme.hero.exploreAll': 'UTFORSKA ALLA TOKENS',
    'meme.hero.updates': 'Uppdateras varje minut',
    'meme.hero.hottestTokens': 'hetaste tokens',
    'meme.hero.explosive': 'EXPLOSIV',
    'meme.hero.hot': 'HET',
    'meme.hero.trending': 'TRENDING',
    'meme.hero.tradeNow': 'HANDLA NU',
    'meme.hero.price': 'PRIS',
    'meme.hero.mcap': 'MCAP',
    
    // News Section
    'news.title': 'Senaste Nyheterna',
    'news.readMore': 'Läs mer',
    'news.source': 'Källa',
    'news.published': 'Publicerad',
    'news.loading': 'Laddar nyheter...',
    'news.error': 'Kunde inte ladda nyheter',
    'news.noArticles': 'Inga artiklar hittades',
    
    // Community Section
    'community.title': 'Gå med i Communityn',
    'community.subtitle': 'Anslut dig till tusentals kryptoentusiaster',
    'community.discord': 'Discord Server',
    'community.telegram': 'Telegram Grupp',
    'community.twitter': 'Twitter Community',
    'community.youtube': 'YouTube Kanal',
    'community.join': 'Gå med',
    'community.members': 'medlemmar',
    'community.online': 'online',
    
    // Footer
    'footer.about': 'Om Oss',
    'footer.contact': 'Kontakt',
    'footer.terms': 'Villkor',
    'footer.privacy': 'Integritet',
    'footer.support': 'Support',
    'footer.api': 'API',
    'footer.blog': 'Blogg',
    'footer.careers': 'Karriär',
    'footer.copyright': '© 2024 Crypto Network Sweden. Alla rättigheter förbehållna.',
    
    // Tools Page
    'tools.title': 'Krypto Verktyg',
    'tools.calculator': 'Kalkylator',
    'tools.converter': 'Omvandlare',
    'tools.alerts': 'Prisvarningar',
    'tools.portfolio': 'Portfolio Tracker',
    'tools.news': 'Nyheter',
    'tools.calendar': 'Kalender',
    'tools.learn': 'Lär dig',
    'tools.dca': 'DCA Kalkylator',
    
    // Trading
    'trading.buy': 'Köp',
    'trading.sell': 'Sälj',
    'trading.amount': 'Mängd',
    'trading.total': 'Totalt',
    'trading.orderBook': 'Orderbok',
    'trading.recentTrades': 'Senaste affärer',
    'trading.openOrders': 'Öppna order',
    'trading.orderHistory': 'Orderhistorik',
    'trading.balance': 'Saldo',
    'trading.available': 'Tillgängligt',
    'trading.chart': 'Diagram',
    'trading.analysis': 'Analys',
    
    // Wallet
    'wallet.connect': 'Anslut Plånbok',
    'wallet.connected': 'Ansluten',
    'wallet.disconnect': 'Koppla från',
    'wallet.address': 'Adress',
    'wallet.balance': 'Saldo',
    'wallet.transactions': 'Transaktioner',
    'wallet.send': 'Skicka',
    'wallet.receive': 'Ta emot',
    'wallet.swap': 'Växla',
    
    // Common
    'common.loading': 'Laddar...',
    'common.error': 'Fel uppstod',
    'common.retry': 'Försök igen',
    'common.close': 'Stäng',
    'common.open': 'Öppna',
    'common.save': 'Spara',
    'common.cancel': 'Avbryt',
    'common.confirm': 'Bekräfta',
    'common.search': 'Sök',
    'common.filter': 'Filtrera',
    'common.sort': 'Sortera',
    'common.connect': 'Anslut',
    'common.connected': 'Ansluten',
    'common.disconnect': 'Koppla från',
    'common.view': 'Visa',
    'common.edit': 'Redigera',
    'common.delete': 'Ta bort',
    'common.add': 'Lägg till',
    'common.remove': 'Ta bort',
    'common.update': 'Uppdatera',
    'common.refresh': 'Uppdatera',
    'common.back': 'Tillbaka',
    'common.next': 'Nästa',
    'common.previous': 'Föregående',
    'common.submit': 'Skicka',
    'common.reset': 'Återställ',
    'common.select': 'Välj',
    'common.copy': 'Kopiera',
    'common.share': 'Dela',
    'common.export': 'Exportera',
    'common.import': 'Importera',
    'common.download': 'Ladda ner',
    'common.upload': 'Ladda upp',
    'common.settings': 'Inställningar',
    'common.help': 'Hjälp',
    'common.about': 'Om',
    'common.contact': 'Kontakt',
    'common.support': 'Support',
    'common.more': 'Mer',
    'common.less': 'Mindre',
    'common.show': 'Visa',
    'common.hide': 'Dölj',
    'common.expand': 'Expandera',
    'common.collapse': 'Kollapsa',
    'common.yes': 'Ja',
    'common.no': 'Nej',
    'common.ok': 'OK',
    'common.continue': 'Fortsätt',
    'common.finish': 'Slutför',
    'common.start': 'Starta',
    'common.stop': 'Stoppa',
    'common.pause': 'Pausa',
    'common.play': 'Spela',
    'common.record': 'Spela in',
    'common.live': 'Live',
    'common.offline': 'Offline',
    'common.online': 'Online',
    'common.public': 'Offentlig',
    'common.private': 'Privat',
    'common.enabled': 'Aktiverad',
    'common.disabled': 'Inaktiverad',
    'common.active': 'Aktiv',
    'common.inactive': 'Inaktiv',
    'common.new': 'Ny',
    'common.old': 'Gammal',
    'common.latest': 'Senaste',
    'common.oldest': 'Äldsta',
    'common.popular': 'Populär',
    'common.trending': 'Trending',
    'common.featured': 'Utvald',
    'common.recommended': 'Rekommenderad'
  },
  en: {
    // Site metadata
    'site.title': 'Crypto Network Sweden - Your Crypto Community | Bitcoin, Ethereum & DeFi',
    'site.description': 'Sweden\'s leading crypto community. Learn about cryptocurrencies, follow the market in real-time and meet new friends with the same passion for Web3. Join today!',
    
    // Header & Navigation
    'nav.home': 'Home',
    'nav.market': 'Market',
    'nav.portfolio': 'Portfolio',
    'nav.trading': 'Trading',
    'nav.memeZone': 'Meme Zone',
    'nav.createToken': 'Create Token',
    'nav.tools': 'Tools',
    'nav.news': 'News',
    'nav.community': 'Community',
    'nav.wallet': 'Wallet',
    'nav.mainPages': 'Main Pages',
    
    // Descriptions
    'desc.home': 'Homepage',
    'desc.market': 'Market overview',
    'desc.portfolio': 'My portfolio & watchlist',
    'desc.trading': 'Trading & analysis',
    'desc.memeZone': 'Meme coins & tokens',
    'desc.createToken': 'Create your own token',
    'desc.tools': 'Crypto tools',
    'desc.news': 'Latest news',
    'desc.community': 'Community & forum',
    
    // Portfolio Page
    'portfolio.title': 'Portfolio',
    'portfolio.overview': 'Overview',
    'portfolio.holdings': 'Holdings',
    'portfolio.transactions': 'Transactions',
    'portfolio.watchlist': 'Watchlist',
    'portfolio.totalValue': 'Total Value',
    'portfolio.totalPnL': 'Total PnL',
    'portfolio.dayChange': '24h Change',
    'portfolio.hideValues': 'Hide Values',
    'portfolio.showValues': 'Show Values',
    'portfolio.refresh': 'Refresh',
    'portfolio.noWallet': 'No wallet connected',
    'portfolio.connectWallet': 'Connect a Solana wallet to view your portfolio',
    'portfolio.error': 'Error fetching portfolio data',
    'portfolio.tryAgain': 'Try again in a moment',
    'portfolio.updated': 'Data updated',
    'portfolio.updateFailed': 'Could not update data',
    'portfolio.connected': 'Connected',
    'portfolio.disconnected': 'Disconnected',
    
    // Market Overview Page
    'market.title': 'Market Overview',
    'market.description': 'Real-time overview of the crypto market',
    'market.search': 'Search cryptocurrency...',
    'market.all': 'All',
    'market.gainers': 'Gainers',
    'market.losers': 'Losers',
    'market.favorites': 'Favorites',
    'market.name': 'Name',
    'market.price': 'Price',
    'market.change24h': '24h %',
    'market.volume': 'Volume',
    'market.marketCap': 'Market Cap',
    'market.supply': 'Supply',
    'market.rank': 'Rank',
    'market.loading': 'Loading market data...',
    'market.error': 'Could not load market data',
    'market.noResults': 'No results found',
    'market.addToWatchlist': 'Add to watchlist',
    'market.removeFromWatchlist': 'Remove from watchlist',
    'market.viewChart': 'View chart',
    'market.trade': 'Trade',
    'market.tableView': 'Table view',
    'market.gridView': 'Grid view',
    'market.cryptocurrencies': 'Cryptocurrencies',
    'market.showing': 'Showing',
    'market.of': 'of',
    'market.top10': 'TOP 10',
    'market.trending': 'Trending',
    'market.meme': 'Meme',
    'market.gainersShort': 'Gainers',
    'market.losersShort': 'Losers',
    'market.allShort': 'All',
    'market.totalMarketCap': 'Total Market Cap',
    'market.fearGreed': 'Fear & Greed Index',
    'market.altSeason': 'Alt Season',
    'market.btcDominance': 'BTC Dominance',
    'market.volume24h': 'Volume 24h',
    'market.trading': 'Trading',
    'market.btcDom': 'BTC Dom',
    'market.btcSeason': 'BTC Season',
    'market.altSeasonIndex': 'Alt Season Index',
    'market.liveCryptoData': 'Live crypto data and market analysis',
    
    // Hero Section
    'hero.title': 'Sweden\'s Crypto Community',
    'hero.subtitle': 'Learn, trade and grow with Sweden\'s leading crypto community',
    'hero.cta': 'Get Started',
    'hero.exploreMarket': 'Explore Market',
    'hero.livePrices': 'Live Prices',
    'hero.realTimeData': 'Real-time Data',
    'hero.secureTrading': 'Secure Trading',
    
    // Meme Hero
    'meme.hero.title': 'HOTTEST TOKENS',
    'meme.hero.subtitle': 'The 20 most explosive meme tokens right now – Live market data',
    'meme.hero.liveUpdates': 'LIVE UPDATES',
    'meme.hero.loading': 'Loading hottest tokens...',
    'meme.hero.tryAgain': 'Try Again',
    'meme.hero.exploreAll': 'EXPLORE ALL TOKENS',
    'meme.hero.updates': 'Updates every minute',
    'meme.hero.hottestTokens': 'hottest tokens',
    'meme.hero.explosive': 'EXPLOSIVE',
    'meme.hero.hot': 'HOT',
    'meme.hero.trending': 'TRENDING',
    'meme.hero.tradeNow': 'TRADE NOW',
    'meme.hero.price': 'PRICE',
    'meme.hero.mcap': 'MCAP',
    
    // News Section
    'news.title': 'Latest News',
    'news.readMore': 'Read more',
    'news.source': 'Source',
    'news.published': 'Published',
    'news.loading': 'Loading news...',
    'news.error': 'Could not load news',
    'news.noArticles': 'No articles found',
    
    // Community Section
    'community.title': 'Join the Community',
    'community.subtitle': 'Connect with thousands of crypto enthusiasts',
    'community.discord': 'Discord Server',
    'community.telegram': 'Telegram Group',
    'community.twitter': 'Twitter Community',
    'community.youtube': 'YouTube Channel',
    'community.join': 'Join',
    'community.members': 'members',
    'community.online': 'online',
    
    // Footer
    'footer.about': 'About Us',
    'footer.contact': 'Contact',
    'footer.terms': 'Terms',
    'footer.privacy': 'Privacy',
    'footer.support': 'Support',
    'footer.api': 'API',
    'footer.blog': 'Blog',
    'footer.careers': 'Careers',
    'footer.copyright': '© 2024 Crypto Network Sweden. All rights reserved.',
    
    // Tools Page
    'tools.title': 'Crypto Tools',
    'tools.calculator': 'Calculator',
    'tools.converter': 'Converter',
    'tools.alerts': 'Price Alerts',
    'tools.portfolio': 'Portfolio Tracker',
    'tools.news': 'News',
    'tools.calendar': 'Calendar',
    'tools.learn': 'Learn',
    'tools.dca': 'DCA Calculator',
    
    // Trading
    'trading.buy': 'Buy',
    'trading.sell': 'Sell',
    'trading.amount': 'Amount',
    'trading.total': 'Total',
    'trading.orderBook': 'Order Book',
    'trading.recentTrades': 'Recent Trades',
    'trading.openOrders': 'Open Orders',
    'trading.orderHistory': 'Order History',
    'trading.balance': 'Balance',
    'trading.available': 'Available',
    'trading.chart': 'Chart',
    'trading.analysis': 'Analysis',
    
    // Wallet
    'wallet.connect': 'Connect Wallet',
    'wallet.connected': 'Connected',
    'wallet.disconnect': 'Disconnect',
    'wallet.address': 'Address',
    'wallet.balance': 'Balance',
    'wallet.transactions': 'Transactions',
    'wallet.send': 'Send',
    'wallet.receive': 'Receive',
    'wallet.swap': 'Swap',
    
    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error occurred',
    'common.retry': 'Try again',
    'common.close': 'Close',
    'common.open': 'Open',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.confirm': 'Confirm',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.sort': 'Sort',
    'common.connect': 'Connect',
    'common.connected': 'Connected',
    'common.disconnect': 'Disconnect',
    'common.view': 'View',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.add': 'Add',
    'common.remove': 'Remove',
    'common.update': 'Update',
    'common.refresh': 'Refresh',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.submit': 'Submit',
    'common.reset': 'Reset',
    'common.select': 'Select',
    'common.copy': 'Copy',
    'common.share': 'Share',
    'common.export': 'Export',
    'common.import': 'Import',
    'common.download': 'Download',
    'common.upload': 'Upload',
    'common.settings': 'Settings',
    'common.help': 'Help',
    'common.about': 'About',
    'common.contact': 'Contact',
    'common.support': 'Support',
    'common.more': 'More',
    'common.less': 'Less',
    'common.show': 'Show',
    'common.hide': 'Hide',
    'common.expand': 'Expand',
    'common.collapse': 'Collapse',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.ok': 'OK',
    'common.continue': 'Continue',
    'common.finish': 'Finish',
    'common.start': 'Start',
    'common.stop': 'Stop',
    'common.pause': 'Pause',
    'common.play': 'Play',
    'common.record': 'Record',
    'common.live': 'Live',
    'common.offline': 'Offline',
    'common.online': 'Online',
    'common.public': 'Public',
    'common.private': 'Private',
    'common.enabled': 'Enabled',
    'common.disabled': 'Disabled',
    'common.active': 'Active',
    'common.inactive': 'Inactive',
    'common.new': 'New',
    'common.old': 'Old',
    'common.latest': 'Latest',
    'common.oldest': 'Oldest',
    'common.popular': 'Popular',
    'common.trending': 'Trending',
    'common.featured': 'Featured',
    'common.recommended': 'Recommended'
  }
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'sv';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  const value = {
    language,
    setLanguage,
    t
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};